import { execSync, spawn } from 'node:child_process';
import { cpSync, mkdtempSync, rmSync } from 'node:fs';
import path from 'node:path';
import os from 'node:os';
const root = process.env.PLAYWRIGHT_ROOT ?? execSync('npm root -g').toString().trim();
const { chromium } = await import(`${root}/playwright/index.mjs`);
const [repo, outDir] = process.argv.slice(2);
const site = mkdtempSync(path.join(os.tmpdir(), 'qa5-'));
cpSync(repo, site, { recursive: true, filter: (src) => !/\/\.git(\/|$)|\/\.qa-evidence|\/\.agents/.test(src) });
const PORT = 8021;
let server;
const startServer = () => { server = spawn('python3', ['-m', 'http.server', String(PORT), '--bind', '127.0.0.1'], { cwd: site, stdio: 'ignore' }); };
const stopServer = () => new Promise((ok) => { server.once('exit', ok); server.kill(); });
const wait = (ms) => new Promise((ok) => setTimeout(ok, ms));
startServer(); await wait(800);
const browser = await chromium.launch();
const context = await browser.newContext({ viewport: { width: 1280, height: 900 } });
const page = await context.newPage();
const errors = [];
page.on('pageerror', (error) => errors.push(error.message));
const base = `http://127.0.0.1:${PORT}/`;
const r = {};
await page.goto(base + 'cursos.html');
await page.evaluate(() => navigator.serviceWorker.ready);
await page.reload();
await page.evaluate(() => navigator.serviceWorker.ready);
const button = page.locator('.offline-btn[data-slug="git"]');
await button.waitFor();
await stopServer();
await button.click();
await page.waitForFunction(() => document.querySelector('.offline-btn[data-slug="git"]').dataset.state !== 'saving', null, { timeout: 60000 });
await wait(500);
r.sinServidor = { state: await button.getAttribute('data-state'), label: (await button.innerText()).trim(), title: await button.getAttribute('title'), status: await page.evaluate(() => { const el = document.getElementById('offline-status'); return el ? el.getAttribute('role') + ': ' + el.textContent : 'sin región'; }) };
await button.screenshot({ path: `${outDir}/1-sin-servidor.png` });
startServer(); await wait(800);
await button.click();
await page.waitForFunction(() => document.querySelector('.offline-btn[data-slug="git"]').dataset.state === 'saved', null, { timeout: 60000 }).catch(() => {});
r.reintento = { state: await button.getAttribute('data-state'), label: (await button.innerText()).trim() };
await button.screenshot({ path: `${outDir}/2-reintento.png` });
const other = page.locator('.offline-btn[data-slug="docker"]');
await page.evaluate(() => { ServiceWorker.prototype.postMessage = () => {}; });
await page.evaluate(() => caches.open('academia-content').then((c) => c.keys()).then((k) => Promise.all(k.filter((r) => r.url.includes('/tutorials/docker')).map((r) => caches.open('academia-content').then((c) => c.delete(r))))));
const started = Date.now();
await other.click();
await page.waitForFunction(() => document.querySelector('.offline-btn[data-slug="docker"]').dataset.state !== 'saving', null, { timeout: 60000 });
await wait(300);
r.workerMudo = { seconds: Math.round((Date.now() - started) / 1000), state: await other.getAttribute('data-state'), label: (await other.innerText()).trim(), title: await other.getAttribute('title') };
await other.screenshot({ path: `${outDir}/3-worker-mudo.png` });
await page.goto(base + 'offline.html');
await page.evaluate(() => navigator.serviceWorker.ready);
await stopServer();
await page.click('#offline-all-btn');
await page.waitForFunction(() => !document.getElementById('offline-all-btn').disabled, null, { timeout: 120000 });
r.todoSinServidor = { copy: await page.innerText('.offline-all__copy'), button: await page.innerText('#offline-all-btn'), status: await page.evaluate(() => document.getElementById('offline-status')?.textContent ?? 'sin región') };
await page.locator('.offline-all').screenshot({ path: `${outDir}/4-todo-sin-servidor.png` });
startServer(); await wait(800);
await page.click('#offline-all-btn');
await page.waitForFunction(() => !document.getElementById('offline-all-btn').disabled, null, { timeout: 180000 });
r.todoConServidor = { copy: await page.innerText('.offline-all__copy'), button: await page.innerText('#offline-all-btn') };
r.errors = errors;
console.log(JSON.stringify(r, null, 2));
await browser.close(); await stopServer(); rmSync(site, { recursive: true, force: true });
