import { execSync } from 'node:child_process';
const root = process.env.PLAYWRIGHT_ROOT ?? execSync('npm root -g').toString().trim();
const { chromium } = await import(`${root}/playwright/index.mjs`);
const [base, outDir] = process.argv.slice(2);
const browser = await chromium.launch();
const page = await (await browser.newContext({ viewport: { width: 1280, height: 900 }, serviceWorkers: 'block' })).newPage();
const errors = [];
page.on('pageerror', (error) => errors.push(error.message));
const reto = async (slug, title) => {
  await page.goto(`${base}curso.html?slug=${slug}`);
  const card = page.locator('.practica__reto', { hasText: title }).first();
  await card.locator('summary').first().click();
  await card.scrollIntoViewIfNeeded();
  await card.screenshot({ path: `${outDir}/${slug}.png` });
  return (await card.innerText()).replace(/\s+/g, ' ');
};
const result = {};
result.linux = await reto('terminal-linux', 'El fichero que se come el disco');
result.k8s = await reto('k8s-para-devs', 'El deploy roto');
result.go = await reto('go', 'Cuenta en paralelo');
result.maquina = await reto('la-maquina', 'Filas contra columnas');
await page.goto(`${base}tutorials/maq-cpu.html#experimento`);
const section = page.locator('#experimento');
result.maqCpuCode = (await page.locator('#experimento ~ .code-block code').first().innerText()).slice(0, 220);
result.maqCpuCallout = await page.locator('.callout__title', { hasText: 'fila a fila' }).count();
await page.locator('#experimento ~ .code-block').first().screenshot({ path: `${outDir}/maq-cpu-codigo.png` });
result.errors = errors;
console.log(JSON.stringify(result, null, 2));
await browser.close();
