import { execSync } from 'node:child_process';
const root = process.env.PLAYWRIGHT_ROOT ?? execSync('npm root -g').toString().trim();
const { chromium } = await import(`${root}/playwright/index.mjs`);
const [base, outDir] = process.argv.slice(2);
const browser = await chromium.launch();
const page = await (await browser.newContext({ viewport: { width: 1280, height: 900 }, serviceWorkers: 'block' })).newPage();
const errors = [];
page.on('pageerror', (error) => errors.push(error.message));
await page.goto(`${base}tutorials/cc-hooks-y-permisos.html`);
const r = {};
r.diagrama = (await page.locator('#hooks ~ .diagram .flow__node').nth(1).innerText()).replace(/\s+/g, ' ');
await page.locator('#hooks ~ .diagram').first().screenshot({ path: `${outDir}/diagrama.png` });
r.settingsHooks = await page.locator('code', { hasText: '"PreToolUse"' }).count();
r.calloutSolo2 = await page.locator('.callout__title', { hasText: 'Solo el 2 bloquea' }).count();
r.calloutDeny = await page.locator('.callout__title', { hasText: /deny/ }).allInnerTexts();
if (r.calloutSolo2) await page.locator('.callout', { hasText: 'Solo el 2 bloquea' }).screenshot({ path: `${outDir}/callout-exit2.png` });
const deny = page.locator('.callout', { hasText: 'Hasta dónde llega un deny' });
if (await deny.count()) await deny.screenshot({ path: `${outDir}/callout-deny.png` });
r.checkExit1 = await page.locator('text=termina con exit 1').count();
r.errors = errors;
console.log(JSON.stringify(r, null, 2));
await browser.close();
