import { execSync } from 'node:child_process';
const root = process.env.PLAYWRIGHT_ROOT ?? execSync('npm root -g').toString().trim();
const { chromium } = await import(`${root}/playwright/index.mjs`);
const [base] = process.argv.slice(2);
const browser = await chromium.launch();
const page = await (await browser.newContext({ viewport: { width: 1280, height: 900 }, serviceWorkers: 'block' })).newPage();
const errors = [];
page.on('pageerror', (error) => errors.push(error.message));
await page.goto(base + 'repaso.html');
const seeded = await page.evaluate(() => {
  localStorage.clear();
  const yesterday = Date.now() - 864e5;
  const repaso = {};
  const enunciados = {};
  for (const [slug, qs] of Object.entries(window.MENTORAI_CHECKS).slice(0, 20)) qs.forEach((q, i) => { if (i % 2 === 0) { repaso[`c:${slug}:${i}`] = { s: 2, d: yesterday, f: 1 }; enunciados[`c:${slug}:${i}`] = q.q; } });
  const [curso, quiz] = Object.entries(window.MENTORAI_QUIZZES)[0];
  quiz.questions.slice(0, 6).forEach((q, i) => { repaso[`q:${curso}:${i}`] = { s: 1, d: yesterday, f: 0 }; enunciados[`q:${curso}:${i}`] = q.q; });
  repaso['ruta:backend'] = { s: 1, d: yesterday, f: 0 };
  localStorage.setItem('academia-repaso', JSON.stringify(repaso));
  localStorage.setItem('academia-practica', JSON.stringify({ git: { 0: true, 2: true } }));
  return { claves: Object.keys(repaso).length, enunciados };
});
await page.reload();
await page.waitForTimeout(500);
const r = { sembradas: seeded.claves };
r.repasoHoy = (await page.locator('main').innerText()).match(/(\d+)\s+(para hoy|pendientes|esperando)/i)?.[0] ?? 'sin cifra';
await page.goto(base + 'perfil.html');
await page.waitForTimeout(300);
r.perfilResumen = (await page.locator('.perfil__resumen').innerText().catch(() => '')).trim();
await page.goto(base + 'curso.html?slug=git');
await page.waitForTimeout(500);
r.retosGit = (await page.locator('.practica').innerText().catch(() => '')).match(/\d+\s+de\s+\d+/)?.[0] ?? 'sin cifra';
r.retosMarcados = await page.$$eval('.practica__reto--done .practica__num', (els) => els.map((el) => el.textContent.trim()));
r.estado = await page.evaluate((enunciados) => {
  const repaso = JSON.parse(localStorage.getItem('academia-repaso'));
  const practica = JSON.parse(localStorage.getItem('academia-practica'));
  const resolver = (key) => { const [k, scope, id] = key.split(':'); const qs = k === 'c' ? window.MENTORAI_CHECKS[scope] : window.MENTORAI_QUIZZES[scope]?.questions; return (qs ?? []).find((q) => q.id === id)?.q ?? (qs ?? [])[Number(id)]?.q; };
  const keys = Object.keys(repaso);
  const malAsignadas = Object.entries(enunciados).filter(([oldKey, texto]) => !keys.some((key) => key.split(':').slice(0, 2).join(':') === oldKey.split(':').slice(0, 2).join(':') && resolver(key) === texto)).length;
  return { claves: keys.length, posicionalesRestantes: keys.filter((k) => /^[cq]:.+:\d+$/.test(k)).length, ruta: Boolean(repaso['ruta:backend']), malAsignadas, practica };
}, seeded.enunciados);
r.errors = errors;
console.log(JSON.stringify(r, null, 2));
await browser.close();
