/* ============================================================
   Manifiesto de tutoriales
   ------------------------------------------------------------
   Única fuente de verdad del catálogo. La portada (index.html)
   se construye sola a partir de esta lista: filtros, conteos
   por categoría y tarjetas. Para añadir un tutorial, copia un
   objeto y rellénalo. No hace falta tocar nada más del catálogo.

   Campos:
     slug         identificador corto (= nombre del .html)
     title        título visible
     description  resumen de 1-2 frases
     href         ruta a la página del tutorial
     categories   lista para filtrar (genera los chips sola)
     topic        tema principal (etiqueta legible)
     tags         etiquetas decorativas de la tarjeta
     level         "Principiante" | "Intermedio" | "Avanzado"
     minutes      minutos de lectura
     icon         clave de icono (ver ICONS en main.js)
     status       "published" | "soon"
     date         fecha ISO (ordena el catálogo, más nuevo arriba)
     featured     true para resaltar como "Nuevo" (el más reciente)
     popular      true para curar la sección "Destacados" de la portada
   ============================================================ */

window.ACADEMIA_TUTORIALS = [
  {
    slug: "extensiones-php",
    featured: true,
    title: "Extensiones de PHP: qué son y cuáles importan",
    description:
      "Qué es una extensión (un módulo en C que enchufa al motor), cómo se carga, la diferencia entre las del core y las de PECL, cómo ver las activas con php -m y el puñado que necesitas de verdad en producción.",
    href: "tutorials/extensiones-php.html",
    categories: ["php", "runtime"],
    topic: "PHP por dentro",
    tags: ["Extensiones", "PECL", "php.ini"],
    level: "Intermedio",
    minutes: 13,
    icon: "code",
    status: "published",
    date: "2026-06-22",
  },
  {
    slug: "php-fpm",
    featured: true,
    title: "SAPIs y PHP-FPM a fondo",
    description:
      "Qué es un SAPI, en qué se diferencian CLI, mod_php, CGI y FPM, cómo FastCGI reutiliza procesos vivos, los modos de los pools (static/dynamic/ondemand), cómo dimensionar max_children y por qué PHP es shared-nothing.",
    href: "tutorials/php-fpm.html",
    categories: ["php", "runtime"],
    topic: "PHP por dentro",
    tags: ["PHP-FPM", "FastCGI", "Pools"],
    level: "Avanzado",
    minutes: 16,
    icon: "bolt",
    status: "published",
    date: "2026-06-22",
  },
  {
    slug: "memoria-php",
    featured: true,
    title: "Cómo gestiona la memoria PHP",
    description:
      "El gestor de Zend y la arena por request, qué es memory_limit de verdad, los zvals y el refcounting, copy-on-write y el recolector de ciclos. Por qué liberar memoria en PHP es casi gratis.",
    href: "tutorials/memoria-php.html",
    categories: ["php", "runtime"],
    topic: "PHP por dentro",
    tags: ["Memoria", "Refcount", "Copy-on-write"],
    level: "Avanzado",
    minutes: 16,
    icon: "code",
    status: "published",
    date: "2026-06-22",
  },
  {
    slug: "workers-php",
    featured: true,
    title: "Workers y modelos de ejecución en PHP",
    description:
      "Los dos sentidos de worker (los de FPM y los de cola), cómo se mantienen vivos con supervisor, el modelo long-running de Swoole y RoadRunner y por qué un worker que no muere se reinicia cada N jobs.",
    href: "tutorials/workers-php.html",
    categories: ["php", "runtime"],
    topic: "PHP por dentro",
    tags: ["Workers", "Colas", "Swoole"],
    level: "Avanzado",
    minutes: 15,
    icon: "bolt",
    status: "published",
    date: "2026-06-22",
  },
  {
    slug: "redis-a-fondo",
    featured: true,
    title: "Redis a fondo: estructuras de datos en memoria",
    description:
      "Redis como servidor de estructuras de datos, no solo caché: strings y contadores, listas, sets y sorted sets, hashes, y los especiales (bitmaps, HyperLogLog, streams). TTL, nombrado de claves, atomicidad y persistencia RDB vs AOF.",
    href: "tutorials/redis-a-fondo.html",
    categories: ["infra", "bbdd"],
    topic: "Infraestructura",
    tags: ["Redis", "Estructuras", "Sorted sets"],
    level: "Intermedio",
    minutes: 17,
    icon: "database",
    status: "published",
    date: "2026-06-22",
  },
  {
    slug: "tcp-ip",
    title: "TCP/IP: el cartero fiable de internet",
    description:
      "Por qué TCP entrega datos en orden y sin pérdidas sobre una red que pierde, desordena y duplica paquetes: el handshake de tres pasos, qué identifican IP y puerto, el control de flujo por ventanas y las causas reales de que una conexión se quede colgada.",
    href: "tutorials/tcp-ip.html",
    categories: ["redes"],
    topic: "Cómo viaja un dato",
    tags: ["TCP", "IP", "Handshake"],
    level: "Avanzado",
    minutes: 15,
    icon: "signal",
    status: "published",
    date: "2026-06-21",
  },
  {
    slug: "http-a-fondo",
    title: "HTTP a fondo: métodos, estados y caché",
    description:
      "El protocolo de texto que mueve la web: anatomía de petición y respuesta, qué método usar y cuándo, los códigos de estado que de verdad importan, cómo funciona la caché de cabeceras y por qué HTTP no tiene estado (cookies vs tokens).",
    href: "tutorials/http-a-fondo.html",
    categories: ["redes"],
    topic: "Cómo viaja un dato",
    tags: ["HTTP", "Métodos", "Caché"],
    level: "Intermedio",
    minutes: 16,
    icon: "signal",
    status: "published",
    date: "2026-06-21",
  },
  {
    slug: "url-a-fondo",
    popular: true,
    title: "Qué pasa al escribir una URL",
    description:
      "El viaje completo de pulsar Enter a ver la página: anatomía de una URL, resolución DNS, el handshake de TCP, el cifrado de TLS y la petición HTTP final, con los errores típicos en cada eslabón de la cadena.",
    href: "tutorials/url-a-fondo.html",
    categories: ["redes"],
    topic: "Cómo viaja un dato",
    tags: ["DNS", "TLS", "HTTP"],
    level: "Intermedio",
    minutes: 14,
    icon: "signal",
    status: "published",
    date: "2026-06-21",
  },
  {
    slug: "memoria",
    title: "Memoria: stack, heap, virtual y caché",
    description:
      "La diferencia entre stack y heap, qué es la memoria virtual y por qué cada proceso cree tener la RAM para él solo, qué es la caché de CPU y la localidad de referencia, y cómo se nota en PHP (memory_limit, copy-on-write).",
    href: "tutorials/memoria.html",
    categories: ["sistemas"],
    topic: "El sistema por debajo",
    tags: ["Stack", "Heap", "Caché"],
    level: "Intermedio",
    minutes: 15,
    icon: "code",
    status: "published",
    date: "2026-06-21",
  },
  {
    slug: "async-event-loop",
    title: "Async y el event loop",
    description:
      "Por qué un hilo por conexión no escala, qué es el event loop, qué significa I/O no bloqueante, cuándo el async brilla y cuándo bloquear el loop lo arruina, y dónde encaja PHP entre FPM síncrono y Swoole/ReactPHP.",
    href: "tutorials/async-event-loop.html",
    categories: ["sistemas"],
    topic: "El sistema por debajo",
    tags: ["Async", "Event loop", "Swoole"],
    level: "Avanzado",
    minutes: 14,
    icon: "code",
    status: "published",
    date: "2026-06-21",
  },
  {
    slug: "concurrencia",
    popular: true,
    title: "Concurrencia: el bug que solo pasa en prod",
    description:
      "Race conditions explicadas con un ejemplo de stock, qué es una sección crítica y cómo la protege un mutex, qué es una operación atómica, cómo aparecen estas carreras en PHP vía la base de datos y qué es un deadlock.",
    href: "tutorials/concurrencia.html",
    categories: ["sistemas"],
    topic: "El sistema por debajo",
    tags: ["Race condition", "Mutex", "Deadlock"],
    level: "Avanzado",
    minutes: 15,
    icon: "code",
    status: "published",
    date: "2026-06-21",
  },
  {
    slug: "procesos-hilos",
    title: "Procesos vs hilos: qué comparten y qué no",
    description:
      "Qué es un proceso y qué es un hilo, qué memoria comparten y cuál está aislada, por qué PHP-FPM es multiproceso y no multihilo, y cuánto cuesta crear y conmutar entre unos y otros.",
    href: "tutorials/procesos-hilos.html",
    categories: ["sistemas"],
    topic: "El sistema por debajo",
    tags: ["Procesos", "Hilos", "PHP-FPM"],
    level: "Intermedio",
    minutes: 14,
    icon: "code",
    status: "published",
    date: "2026-06-21",
  },
  {
    slug: "modelado-relacional",
    title: "Modelado relacional: normalizar sin dogma",
    description:
      "Claves primarias y foráneas, relaciones uno a muchos y muchos a muchos, normalización de la 1FN a la 3FN explicada sin dogma y cuándo desnormalizar a propósito.",
    href: "tutorials/modelado-relacional.html",
    categories: ["bbdd"],
    topic: "Bases de datos",
    tags: ["Normalización", "Claves", "Relaciones"],
    level: "Intermedio",
    minutes: 14,
    icon: "database",
    status: "published",
    date: "2026-06-21",
  },
  {
    slug: "transacciones-acid",
    title: "Transacciones y ACID: todo o nada",
    description:
      "Qué garantiza una transacción (ACID), cómo deshacer un cambio a medias con ROLLBACK, los niveles de aislamiento, las lecturas sucias, no repetibles y fantasma, y por qué aparecen los deadlocks.",
    href: "tutorials/transacciones-acid.html",
    categories: ["bbdd"],
    topic: "Bases de datos",
    tags: ["ACID", "Transacciones", "Aislamiento"],
    level: "Avanzado",
    minutes: 16,
    icon: "database",
    status: "published",
    date: "2026-06-21",
  },
  {
    slug: "indices-btree",
    popular: true,
    title: "Índices y B-tree: por qué tu query es lenta",
    description:
      "Por qué una consulta sin índice lee la tabla entera, cómo un B-tree encuentra una fila en pocos saltos, cómo leer un EXPLAIN, el orden de columnas en índices compuestos y cuándo un índice no se usa.",
    href: "tutorials/indices-btree.html",
    categories: ["bbdd"],
    topic: "Bases de datos",
    tags: ["Índices", "B-tree", "EXPLAIN"],
    level: "Intermedio",
    minutes: 15,
    icon: "database",
    status: "published",
    date: "2026-06-21",
  },
  {
    slug: "hashing",
    title: "Hashing: cómo un hashmap busca en O(1)",
    description:
      "Qué hace una función hash, cómo convierte una clave en una posición, qué son las colisiones y cómo se resuelven, el factor de carga y el rehashing, y por qué un hashmap es O(1) de media pero O(n) en el peor caso.",
    href: "tutorials/hashing.html",
    categories: ["algoritmos"],
    topic: "Fundamentos",
    tags: ["Hashing", "Hashmap", "Colisiones"],
    level: "Intermedio",
    minutes: 14,
    icon: "code",
    status: "published",
    date: "2026-06-21",
  },
  {
    slug: "estructuras-datos",
    title: "Estructuras de datos: cuál usar y cuándo",
    description:
      "Array, lista enlazada, hashmap, set, árbol y grafo: qué hace barato y qué caro cada uno, cómo elegir por la operación que domina y por qué el array de PHP es un mapa ordenado.",
    href: "tutorials/estructuras-datos.html",
    categories: ["algoritmos"],
    topic: "Fundamentos",
    tags: ["Estructuras", "Hashmap", "Árboles"],
    level: "Intermedio",
    minutes: 15,
    icon: "code",
    status: "published",
    date: "2026-06-21",
  },
  {
    slug: "big-o",
    popular: true,
    title: "Big-O sin matemáticas: cómo saber si tu código escala",
    description:
      "Qué mide Big-O (cómo crece el coste, no los segundos), las clases que verás en la práctica (O(1), O(log n), O(n), O(n log n), O(n²)) y cómo cazar el O(n²) escondido que mata el rendimiento.",
    href: "tutorials/big-o.html",
    categories: ["algoritmos"],
    topic: "Fundamentos",
    tags: ["Big-O", "Complejidad", "Rendimiento"],
    level: "Intermedio",
    minutes: 14,
    icon: "signal",
    status: "published",
    date: "2026-06-21",
  },
  {
    slug: "numeros-flotantes",
    title: "Números: enteros, complemento a dos y coma flotante",
    description:
      "Por qué un entero no es infinito, cómo se guardan los negativos, qué es el overflow y por qué 0.1 + 0.2 no da 0.3: la coma flotante IEEE-754 y por qué el dinero nunca va en float.",
    href: "tutorials/numeros-flotantes.html",
    categories: ["representacion"],
    topic: "Fundamentos",
    tags: ["Enteros", "IEEE-754", "Overflow"],
    level: "Intermedio",
    minutes: 15,
    icon: "code",
    status: "published",
    date: "2026-06-21",
  },
  {
    slug: "texto-unicode",
    title: "Texto: de ASCII a Unicode y UTF-8",
    description:
      "Por qué un byte se queda corto para el texto, qué resuelve Unicode separando el carácter de sus bytes, cómo UTF-8 lo codifica en 1 a 4 bytes y por qué se rompen acentos y emojis.",
    href: "tutorials/texto-unicode.html",
    categories: ["representacion"],
    topic: "Fundamentos",
    tags: ["Unicode", "UTF-8", "Encoding"],
    level: "Intermedio",
    minutes: 14,
    icon: "code",
    status: "published",
    date: "2026-06-21",
  },
  {
    slug: "bits-y-bytes",
    title: "Bits y bytes: cómo cuenta de verdad un ordenador",
    description:
      "Qué es un bit, por qué ocho forman un byte, cómo se cuenta en binario y hexadecimal, y las operaciones bit a bit (AND, OR, XOR, shifts) detrás de máscaras y permisos.",
    href: "tutorials/bits-y-bytes.html",
    categories: ["representacion"],
    topic: "Fundamentos",
    tags: ["Binario", "Hexadecimal", "Bitwise"],
    level: "Intermedio",
    minutes: 13,
    icon: "code",
    status: "published",
    date: "2026-06-21",
  },
  {
    slug: "rabbitmq",
    title: "RabbitMQ a fondo: exchanges, colas y durabilidad",
    description:
      "Cómo enruta de verdad (exchanges y bindings), las propiedades de las colas, qué hace falta para no perder mensajes (durable + persistente + confirms), acks, DLX y los tipos de cola: classic, quorum y streams.",
    href: "tutorials/rabbitmq.html",
    categories: ["infra", "mensajeria"],
    topic: "Mensajería",
    tags: ["RabbitMQ", "AMQP", "Colas"],
    level: "Avanzado",
    minutes: 18,
    icon: "signal",
    status: "published",
    date: "2026-06-21",
  },
  {
    slug: "inyeccion-dependencias",
    title: "Inyección de dependencias en PHP",
    description:
      "Por qué una clase no debe fabricar sus colaboradores: desacoplar con constructor e interfaces, el contenedor y cómo todo esto hace tus tests triviales.",
    href: "tutorials/inyeccion-dependencias.html",
    categories: ["php", "arquitectura"],
    topic: "PHP",
    tags: ["PHP", "SOLID", "Testing"],
    level: "Intermedio",
    minutes: 16,
    icon: "code",
    status: "published",
    date: "2026-06-21",
  },
  {
    slug: "opcache",
    popular: true,
    title: "OPcache: cómo PHP deja de releer tu código",
    description:
      "Qué es, cómo funciona la caché de opcodes en memoria compartida, cómo configurarlo bien y los errores típicos que matan su efecto.",
    href: "tutorials/opcache.html",
    categories: ["php", "rendimiento"],
    topic: "PHP",
    tags: ["PHP", "Bytecode", "JIT"],
    level: "Intermedio",
    minutes: 15,
    icon: "bolt",
    status: "published",
    date: "2026-06-21",
  },
  {
    slug: "preload",
    title: "Preload: precargar clases al arrancar PHP",
    description:
      "El siguiente paso después de OPcache: dejar tu framework cargado en memoria desde el arranque del proceso.",
    href: "tutorials/preload.html",
    categories: ["php", "rendimiento"],
    topic: "PHP",
    tags: ["PHP", "Rendimiento"],
    level: "Avanzado",
    minutes: 12,
    icon: "signal",
    status: "soon",
    date: "2026-06-20",
  },
  {
    slug: "redis-cache",
    featured: true,
    title: "Redis como caché de aplicación",
    description:
      "El patrón cache-aside paso a paso, por qué el TTL no es opcional, cómo invalidar sin carreras (borrar mejor que reescribir) y los tres fallos clásicos (penetration, avalanche, breakdown) más el cache stampede y su lock.",
    href: "tutorials/redis-cache.html",
    categories: ["infra", "rendimiento"],
    topic: "Infraestructura",
    tags: ["Redis", "Caché", "TTL"],
    level: "Intermedio",
    minutes: 15,
    icon: "database",
    status: "published",
    date: "2026-06-22",
  },
];
