/* ============================================================
   Manifiesto de tutoriales
   ------------------------------------------------------------
   Única fuente de verdad del catálogo. La portada (index.html)
   se construye sola a partir de esta lista: filtros, conteos
   por categoría y tarjetas. Para añadir un tutorial, copia un
   objeto y rellénalo. No hace falta tocar nada más del catálogo.

   Campos:
     slug         identificador corto (= nombre del .html)
     title        título visible
     description  resumen de 1-2 frases
     href         ruta a la página del tutorial
     categories   lista para filtrar (genera los chips sola)
     topic        tema principal (etiqueta legible)
     tags         etiquetas decorativas de la tarjeta
     level         "Principiante" | "Intermedio" | "Avanzado"
     minutes      minutos de lectura
     icon         clave de icono (ver ICONS en assets/js/modules/catalog.js)
     status       "published" | "soon"
     date         fecha ISO (ordena el catálogo, más nuevo arriba)
     featured     true para resaltar como "Nuevo" (el más reciente)
     popular      true para curar la sección "Destacados" de la portada
   ============================================================ */

window.ACADEMIA_TUTORIALS = [
  {
    slug: "git-comandos-esenciales",
    featured: true,
    title: "Git: comandos del día a día",
    description:
      "La chuleta de comandos de Git para tener a mano: configurar, empezar un repo, los cambios del día a día (add, commit, status, diff), inspeccionar el historial y sincronizar con el remoto (push, pull, fetch). Cada comando con qué hace y un ejemplo.",
    href: "tutorials/git-comandos-esenciales.html",
    categories: ["herramientas"],
    topic: "Git",
    tags: ["Git", "Comandos", "Referencia"],
    level: "Principiante",
    minutes: 14,
    icon: "code",
    status: "published",
    date: "2026-06-27",
  },
  {
    slug: "git-ramas-y-flujo",
    title: "Git: ramas y flujo de trabajo",
    description:
      "Cómo funcionan las ramas en Git: crear y cambiar de rama, combinar trabajo con merge frente a rebase, resolver conflictos y el flujo de trabajo con feature branches y pull requests.",
    href: "tutorials/git-ramas-y-flujo.html",
    categories: ["herramientas"],
    topic: "Git",
    tags: ["Git", "Ramas", "Merge"],
    level: "Intermedio",
    minutes: 14,
    icon: "code",
    status: "published",
    date: "2026-06-27",
  },
  {
    slug: "git-deshacer",
    title: "Git: deshacer y rescatar",
    description:
      "Cómo salir de un lío en Git: descartar cambios con restore, reset soft/mixed/hard, revert para deshacer sin reescribir, guardar trabajo a medias con stash, corregir el último commit con amend y recuperar lo perdido con reflog.",
    href: "tutorials/git-deshacer.html",
    categories: ["herramientas"],
    topic: "Git",
    tags: ["Git", "reset", "reflog"],
    level: "Intermedio",
    minutes: 14,
    icon: "code",
    status: "published",
    date: "2026-06-27",
  },
  {
    slug: "contenedor-di",
    title: "El contenedor de DI por dentro",
    description:
      "Cómo funciona un contenedor de inyección de dependencias por dentro: definiciones de servicio, autowiring por reflexión, detección de ciclos, ciclo de vida (shared vs factory, lazy con proxies), compilado vs runtime y la gestión de memoria y GC en FPM frente a workers long-running.",
    href: "tutorials/contenedor-di.html",
    categories: ["php", "arquitectura"],
    topic: "Inyección de dependencias",
    tags: ["DI", "Contenedor", "Reflexión"],
    level: "Avanzado",
    minutes: 18,
    icon: "code",
    status: "published",
    date: "2026-06-27",
  },
  {
    slug: "clean-code-intro",
    title: "Clean Code: escribir para quien lee",
    description:
      "Qué es el código limpio y por qué importa: el código se lee mucho más de lo que se escribe, el coste real del código sucio como deuda diaria y la regla del boy scout. La introducción al curso de Clean Code.",
    href: "tutorials/clean-code-intro.html",
    categories: ["arquitectura"],
    topic: "Clean Code",
    tags: ["Clean Code", "Calidad", "Legibilidad"],
    level: "Intermedio",
    minutes: 13,
    icon: "code",
    status: "published",
    date: "2026-06-27",
  },
  {
    slug: "nombres",
    title: "Nombres con intención",
    description:
      "Naming en código limpio: revelar la intención, evitar la desinformación, nombres pronunciables y buscables, no abreviar y las convenciones para booleanos (is/has/should). El factor que más mueve la legibilidad.",
    href: "tutorials/nombres.html",
    categories: ["arquitectura"],
    topic: "Clean Code",
    tags: ["Clean Code", "Naming", "Legibilidad"],
    level: "Intermedio",
    minutes: 13,
    icon: "code",
    status: "published",
    date: "2026-06-27",
  },
  {
    slug: "funciones-limpias",
    title: "Funciones limpias: pequeñas y de una sola cosa",
    description:
      "Cómo escribir funciones limpias: pequeñas que hacen una sola cosa, con un único nivel de abstracción, pocos argumentos, sin efectos secundarios ocultos, separando comando de consulta y usando early return en vez de anidar.",
    href: "tutorials/funciones-limpias.html",
    categories: ["arquitectura"],
    topic: "Clean Code",
    tags: ["Clean Code", "Funciones", "Early return"],
    level: "Intermedio",
    minutes: 14,
    icon: "code",
    status: "published",
    date: "2026-06-27",
  },
  {
    slug: "comentarios",
    title: "Comentarios: por qué un buen comentario es raro",
    description:
      "El papel de los comentarios en código limpio: por qué la mayoría sobran, los comentarios que mienten, los que suplen un mal nombre y los pocos casos en que un comentario sí aporta (el porqué, no el qué).",
    href: "tutorials/comentarios.html",
    categories: ["arquitectura"],
    topic: "Clean Code",
    tags: ["Clean Code", "Comentarios", "Legibilidad"],
    level: "Intermedio",
    minutes: 12,
    icon: "code",
    status: "published",
    date: "2026-06-27",
  },
  {
    slug: "manejo-errores",
    title: "Manejo de errores: excepciones con criterio",
    description:
      "Manejo de errores en código limpio: excepciones frente a códigos de error, por qué no devolver ni pasar null, excepciones específicas en vez de genéricas, fail fast y separar la lógica del manejo de errores.",
    href: "tutorials/manejo-errores.html",
    categories: ["arquitectura"],
    topic: "Clean Code",
    tags: ["Clean Code", "Excepciones", "Fail fast"],
    level: "Intermedio",
    minutes: 13,
    icon: "code",
    status: "published",
    date: "2026-06-27",
  },
  {
    slug: "code-smells-refactoring",
    title: "Code smells y refactoring seguro",
    description:
      "Catálogo de code smells (duplicación, método largo, clase grande, lista de parámetros larga, feature envy, obsesión por primitivos) y cómo refactorizar con seguridad apoyado en tests: extraer método y clase, reemplazar condicional por polimorfismo.",
    href: "tutorials/code-smells-refactoring.html",
    categories: ["arquitectura"],
    topic: "Clean Code",
    tags: ["Clean Code", "Refactoring", "Code smells"],
    level: "Avanzado",
    minutes: 15,
    icon: "code",
    status: "published",
    date: "2026-06-27",
  },
  {
    slug: "solid-introduccion",
    title: "SOLID: cinco principios para domar el cambio",
    description:
      "Qué es SOLID, de dónde viene (Robert C. Martin) y cuál es el hilo común de los cinco principios: gestionar el cambio y las dependencias. El mapa antes de entrar principio a principio, con el aviso de no sobre-aplicarlos.",
    href: "tutorials/solid-introduccion.html",
    categories: ["arquitectura"],
    topic: "Principios SOLID",
    tags: ["SOLID", "Diseño", "Arquitectura"],
    level: "Intermedio",
    minutes: 13,
    icon: "code",
    status: "published",
    date: "2026-06-27",
  },
  {
    slug: "srp-responsabilidad-unica",
    title: "S — Una sola razón para cambiar",
    description:
      "El principio de responsabilidad única (SRP): una clase debe tener una sola razón para cambiar. La god class que calcula, persiste e imprime, por qué duele y cómo partirla en piezas cohesionadas.",
    href: "tutorials/srp-responsabilidad-unica.html",
    categories: ["arquitectura"],
    topic: "Principios SOLID",
    tags: ["SOLID", "SRP", "Cohesión"],
    level: "Intermedio",
    minutes: 13,
    icon: "code",
    status: "published",
    date: "2026-06-27",
  },
  {
    slug: "ocp-abierto-cerrado",
    title: "O — Abierto a extensión, cerrado a modificación",
    description:
      "El principio abierto/cerrado (OCP): añade comportamiento sin modificar lo que ya funciona. El switch por tipo que crece a cada feature y cómo el polimorfismo y el patrón estrategia lo cierran al cambio.",
    href: "tutorials/ocp-abierto-cerrado.html",
    categories: ["arquitectura"],
    topic: "Principios SOLID",
    tags: ["SOLID", "OCP", "Estrategia"],
    level: "Intermedio",
    minutes: 14,
    icon: "code",
    status: "published",
    date: "2026-06-27",
  },
  {
    slug: "lsp-sustitucion-liskov",
    title: "L — Que un subtipo no traicione al base",
    description:
      "El principio de sustitución de Liskov (LSP): un subtipo debe poder reemplazar al base sin romper expectativas. El caso cuadrado/rectángulo, precondiciones que no se endurecen, postcondiciones que no se debilitan y la herencia que miente.",
    href: "tutorials/lsp-sustitucion-liskov.html",
    categories: ["arquitectura"],
    topic: "Principios SOLID",
    tags: ["SOLID", "LSP", "Herencia"],
    level: "Avanzado",
    minutes: 14,
    icon: "code",
    status: "published",
    date: "2026-06-27",
  },
  {
    slug: "isp-segregacion-interfaces",
    title: "I — Interfaces pequeñas y por rol",
    description:
      "El principio de segregación de interfaces (ISP): ningún cliente debe depender de métodos que no usa. La interfaz gorda que obliga a implementar lo que no toca, y cómo partirla en varias interfaces finas por rol.",
    href: "tutorials/isp-segregacion-interfaces.html",
    categories: ["arquitectura"],
    topic: "Principios SOLID",
    tags: ["SOLID", "ISP", "Interfaces"],
    level: "Intermedio",
    minutes: 13,
    icon: "code",
    status: "published",
    date: "2026-06-27",
  },
  {
    slug: "dip-inversion-dependencias",
    title: "D — Depender de abstracciones, no de detalles",
    description:
      "El principio de inversión de dependencias (DIP): los módulos de alto nivel no dependen de los de bajo nivel, sino ambos de abstracciones. El ejemplo mínimo y el puente hacia la inyección de dependencias y la arquitectura hexagonal.",
    href: "tutorials/dip-inversion-dependencias.html",
    categories: ["arquitectura"],
    topic: "Principios SOLID",
    tags: ["SOLID", "DIP", "Inyección"],
    level: "Intermedio",
    minutes: 12,
    icon: "code",
    status: "published",
    date: "2026-06-27",
  },
  {
    slug: "solid-en-conjunto",
    title: "SOLID en conjunto: cómo encajan los cinco",
    description:
      "Cómo se apoyan entre sí los cinco principios SOLID, los errores comunes al aplicarlos (sobre-ingeniería, abstracciones especulativas) y cuándo NO forzarlos. El cierre que convierte cinco reglas sueltas en criterio de diseño.",
    href: "tutorials/solid-en-conjunto.html",
    categories: ["arquitectura"],
    topic: "Principios SOLID",
    tags: ["SOLID", "Diseño", "Criterio"],
    level: "Avanzado",
    minutes: 13,
    icon: "code",
    status: "published",
    date: "2026-06-27",
  },
  {
    slug: "oop-clases-y-objetos",
    title: "Clases y objetos: el primer pilar de la OOP",
    description:
      "Qué problema resuelve la programación orientada a objetos, la diferencia entre clase y objeto, juntar estado y comportamiento, cómo se instancia, qué es $this, el constructor y la encapsulación con visibilidad public/protected/private en PHP.",
    href: "tutorials/oop-clases-y-objetos.html",
    categories: ["oop"],
    topic: "Orientación a objetos",
    tags: ["OOP", "Encapsulación", "PHP"],
    level: "Principiante",
    minutes: 13,
    icon: "code",
    status: "published",
    date: "2026-06-27",
  },
  {
    slug: "herencia",
    title: "Herencia: reutilizar y especializar",
    description:
      "Cómo funciona la herencia en PHP: extends, reutilizar y especializar, parent::, sobrescribir métodos y el riesgo de las jerarquías profundas. Por qué casi siempre conviene preferir la composición a la herencia.",
    href: "tutorials/herencia.html",
    categories: ["oop"],
    topic: "Orientación a objetos",
    tags: ["OOP", "Herencia", "Composición"],
    level: "Intermedio",
    minutes: 14,
    icon: "code",
    status: "published",
    date: "2026-06-27",
  },
  {
    slug: "polimorfismo",
    title: "Polimorfismo: un mensaje, muchas respuestas",
    description:
      "Polimorfismo en PHP: un mismo mensaje con distintas respuestas según el objeto. Polimorfismo por interfaces, los type hints como contrato y cómo sustituye a las cascadas de condicionales por tipo.",
    href: "tutorials/polimorfismo.html",
    categories: ["oop"],
    topic: "Orientación a objetos",
    tags: ["OOP", "Polimorfismo", "Interfaces"],
    level: "Intermedio",
    minutes: 14,
    icon: "code",
    status: "published",
    date: "2026-06-27",
  },
  {
    slug: "interfaces",
    title: "Interfaces: el contrato que desacopla",
    description:
      "La interfaz como contrato en PHP: qué, no cómo. implements, programar contra interfaces, implementar varias a la vez y la diferencia entre interfaz y herencia. La pieza que conecta el polimorfismo con la inyección de dependencias.",
    href: "tutorials/interfaces.html",
    categories: ["oop"],
    topic: "Orientación a objetos",
    tags: ["OOP", "Interfaces", "Desacoplamiento"],
    level: "Intermedio",
    minutes: 13,
    icon: "code",
    status: "published",
    date: "2026-06-27",
  },
  {
    slug: "clases-abstractas",
    title: "Clases abstractas: plantilla a medio hacer",
    description:
      "Clases y métodos abstractos en PHP: la plantilla parcial (template method), por qué no se instancian y, sobre todo, cuándo elegir una clase abstracta y cuándo una interfaz.",
    href: "tutorials/clases-abstractas.html",
    categories: ["oop"],
    topic: "Orientación a objetos",
    tags: ["OOP", "Abstracción", "Interfaces"],
    level: "Intermedio",
    minutes: 13,
    icon: "code",
    status: "published",
    date: "2026-06-27",
  },
  {
    slug: "tipos-de-clases-php",
    title: "Los tipos de clases de PHP y cuándo usar cada uno",
    description:
      "El zoo de tipos de PHP moderno: clase normal, abstract, final, interface, trait, enum, propiedades readonly y clases anónimas. Qué resuelve cada uno y una tabla de decisión para elegir bien.",
    href: "tutorials/tipos-de-clases-php.html",
    categories: ["oop"],
    topic: "Orientación a objetos",
    tags: ["OOP", "PHP", "enum"],
    level: "Intermedio",
    minutes: 15,
    icon: "code",
    status: "published",
    date: "2026-06-27",
  },
  {
    slug: "object-calisthenics",
    title: "Object Calisthenics: 9 reglas para mejor diseño OO",
    description:
      "Las 9 reglas de Object Calisthenics como ejercicio para mejorar tu diseño orientado a objetos: un nivel de indentación, sin else, envolver primitivos, colecciones de primera clase, ley de Demeter, sin getters/setters y más, con ejemplos en PHP.",
    href: "tutorials/object-calisthenics.html",
    categories: ["arquitectura"],
    topic: "Diseño y arquitectura",
    tags: ["Clean Code", "OOP", "Diseño"],
    level: "Intermedio",
    minutes: 16,
    icon: "code",
    status: "published",
    date: "2026-06-27",
  },
  {
    slug: "conceptos-ia",
    title: "Conceptos de IA: LLM, agente, MCP y RAG",
    description:
      "El mapa del ecosistema de la IA para programar, sin humo: qué es un LLM, qué son los tokens y la ventana de contexto, qué son las herramientas, qué es un agente, qué es MCP, qué es RAG y cuándo hace falta fine-tuning.",
    href: "tutorials/conceptos-ia.html",
    categories: ["ia"],
    topic: "Programar con IA",
    tags: ["LLM", "MCP", "RAG"],
    level: "Principiante",
    minutes: 15,
    icon: "signal",
    status: "published",
    date: "2026-06-27",
  },
  {
    slug: "cqrs-event-sourcing",
    title: "CQRS y Event Sourcing: guardar la historia",
    description:
      "Event sourcing: guardar la secuencia de eventos en vez del estado actual, reconstruir el estado reproduciéndolos, las proyecciones de lectura, su encaje natural con CQRS y los trade-offs reales antes de adoptarlo.",
    href: "tutorials/cqrs-event-sourcing.html",
    categories: ["arquitectura"],
    topic: "Diseño y arquitectura",
    tags: ["Event Sourcing", "CQRS", "Proyecciones"],
    level: "Avanzado",
    minutes: 16,
    icon: "code",
    status: "published",
    date: "2026-06-26",
  },
  {
    slug: "cqrs",
    title: "CQRS: separar lecturas de escrituras",
    description:
      "Separar el modelo de comandos (escritura) del de queries (lectura): por qué puede ayudar, los niveles de adopción (de solo código a almacenes separados) y, sobre todo, cuándo NO usarlo por la complejidad que añade.",
    href: "tutorials/cqrs.html",
    categories: ["arquitectura"],
    topic: "Diseño y arquitectura",
    tags: ["CQRS", "Comandos", "Queries"],
    level: "Avanzado",
    minutes: 15,
    icon: "code",
    status: "published",
    date: "2026-06-26",
  },
  {
    slug: "eventos-de-dominio",
    title: "Eventos de dominio: comunicar sin acoplar",
    description:
      "Qué es un evento de dominio, cómo lo registran los agregados, por qué sirven para mantener la consistencia entre agregados sin acoplarlos y cómo son el puente natural hacia la mensajería asíncrona y la idempotencia.",
    href: "tutorials/eventos-de-dominio.html",
    categories: ["arquitectura"],
    topic: "Diseño y arquitectura",
    tags: ["Eventos", "Agregados", "Consistencia"],
    level: "Avanzado",
    minutes: 15,
    icon: "code",
    status: "published",
    date: "2026-06-26",
  },
  {
    slug: "ddd-tactico",
    title: "DDD táctico: entidades, value objects y agregados",
    description:
      "Los building blocks del DDD táctico con ejemplos en PHP: value object, entidad, agregado y su raíz, repositorio, servicio de dominio y factory. Cuándo usar cada uno y por qué un agregado no es una tabla.",
    href: "tutorials/ddd-tactico.html",
    categories: ["arquitectura"],
    topic: "Diseño y arquitectura",
    tags: ["DDD", "Agregados", "Value Object"],
    level: "Avanzado",
    minutes: 16,
    icon: "code",
    status: "published",
    date: "2026-06-26",
  },
  {
    slug: "ddd-estrategico",
    title: "DDD estratégico: bounded contexts y subdominios",
    description:
      "La mitad estratégica de DDD: partir un dominio grande en bounded contexts, distinguir subdominios core, de soporte y genéricos, dibujar el context map y por qué definir bien los límites importa más que las clases.",
    href: "tutorials/ddd-estrategico.html",
    categories: ["arquitectura"],
    topic: "Diseño y arquitectura",
    tags: ["DDD", "Bounded Context", "Subdominios"],
    level: "Avanzado",
    minutes: 15,
    icon: "code",
    status: "published",
    date: "2026-06-26",
  },
  {
    slug: "ddd-que-es",
    title: "Qué es DDD (y qué no)",
    description:
      "Domain-Driven Design sin humo: el problema que resuelve (modelar dominios complejos), el lenguaje ubicuo, por qué no es solo añadir capas y cuándo NO aplicarlo. La base antes del DDD estratégico y táctico.",
    href: "tutorials/ddd-que-es.html",
    categories: ["arquitectura"],
    topic: "Diseño y arquitectura",
    tags: ["DDD", "Lenguaje ubicuo", "Dominio"],
    level: "Intermedio",
    minutes: 14,
    icon: "code",
    status: "published",
    date: "2026-06-26",
  },
  {
    slug: "hexagonal-en-php",
    title: "Hexagonal en PHP: carpetas, capas y adaptadores",
    description:
      "La arquitectura hexagonal aplicada en PHP: estructura de carpetas por capas (dominio, aplicación, infraestructura), un puerto con dos adaptadores (MySQL y en memoria), cómo testear el dominio aislado y los errores típicos.",
    href: "tutorials/hexagonal-en-php.html",
    categories: ["arquitectura"],
    topic: "Diseño y arquitectura",
    tags: ["Hexagonal", "PHP", "Capas"],
    level: "Avanzado",
    minutes: 16,
    icon: "code",
    status: "published",
    date: "2026-06-26",
  },
  {
    slug: "hexagonal",
    title: "Arquitectura hexagonal: puertos y adaptadores",
    description:
      "La arquitectura hexagonal desde el problema que resuelve (el acoplamiento al mundo exterior): qué son los puertos y los adaptadores, los lados driving y driven, y por qué la inversión de dependencias mantiene el dominio en el centro.",
    href: "tutorials/hexagonal.html",
    categories: ["arquitectura"],
    topic: "Diseño y arquitectura",
    tags: ["Hexagonal", "Puertos", "DIP"],
    level: "Avanzado",
    minutes: 16,
    icon: "code",
    status: "published",
    date: "2026-06-26",
  },
  {
    slug: "criterio-y-riesgos",
    title: "Programar con IA: criterio y riesgos",
    description:
      "Los riesgos de programar con IA y cómo gestionarlos: revisar siempre lo generado, seguridad y secretos, licencias, la deuda técnica silenciosa, los tests como red de seguridad y cuándo es mejor no usar IA.",
    href: "tutorials/criterio-y-riesgos.html",
    categories: ["ia"],
    topic: "Programar con IA",
    tags: ["IA", "Revisión", "Riesgos"],
    level: "Intermedio",
    minutes: 15,
    icon: "signal",
    status: "published",
    date: "2026-06-26",
  },
  {
    slug: "flujo-con-agentes",
    title: "Flujo de trabajo con agentes de código",
    description:
      "Qué es un agente de código (Claude Code y similares) y cómo trabajar con él: el ciclo plan-implementar-revisar, cómo darle el contexto del repositorio, qué herramientas usa y por qué el criterio sigue siendo tuyo.",
    href: "tutorials/flujo-con-agentes.html",
    categories: ["ia"],
    topic: "Programar con IA",
    tags: ["Agentes", "Claude Code", "Flujo"],
    level: "Intermedio",
    minutes: 15,
    icon: "signal",
    status: "published",
    date: "2026-06-26",
  },
  {
    slug: "prompting-para-codigo",
    title: "Prompting para código: cómo pedir bien",
    description:
      "Cómo escribir prompts que dan buen código: aportar contexto, ser específico, dar ejemplos, descomponer el problema, iterar sobre el resultado y pedir el porqué. Técnicas prácticas para programar con IA.",
    href: "tutorials/prompting-para-codigo.html",
    categories: ["ia"],
    topic: "Programar con IA",
    tags: ["Prompting", "Contexto", "Few-shot"],
    level: "Intermedio",
    minutes: 14,
    icon: "signal",
    status: "published",
    date: "2026-06-26",
  },
  {
    slug: "como-piensa-un-llm",
    title: "Cómo «piensa» un LLM al programar",
    description:
      "Qué hace por dentro un modelo de lenguaje cuando le pides código: tokens, ventana de contexto y predicción de la siguiente palabra. Por qué alucina, qué sabe y qué no, y qué implica todo eso para programar con IA.",
    href: "tutorials/como-piensa-un-llm.html",
    categories: ["ia"],
    topic: "Programar con IA",
    tags: ["LLM", "Tokens", "Contexto"],
    level: "Principiante",
    minutes: 14,
    icon: "signal",
    status: "published",
    date: "2026-06-26",
  },
  {
    slug: "tests-que-no-estorban",
    title: "Tests que no estorban: comportamiento y FIRST",
    description:
      "Cómo escribir tests que ayudan en vez de frenar: probar comportamiento y no implementación, los principios FIRST, por qué aparecen los tests frágiles, qué no merece la pena testear y por qué la cobertura es engañosa.",
    href: "tutorials/tests-que-no-estorban.html",
    categories: ["testing"],
    topic: "Testing",
    tags: ["FIRST", "Cobertura", "Frágiles"],
    level: "Avanzado",
    minutes: 15,
    icon: "code",
    status: "published",
    date: "2026-06-26",
  },
  {
    slug: "test-doubles",
    title: "Dobles de test: dummy, stub, mock, spy y fake",
    description:
      "Qué son los dobles de test y para qué sirve cada uno: dummy, stub, spy, mock y fake. Cuándo usar cada tipo, por qué no conviene sobre-mockear y la regla de no falsear lo que no es tuyo.",
    href: "tutorials/test-doubles.html",
    categories: ["testing"],
    topic: "Testing",
    tags: ["Mocks", "Stubs", "Fakes"],
    level: "Intermedio",
    minutes: 14,
    icon: "code",
    status: "published",
    date: "2026-06-26",
  },
  {
    slug: "tipos-de-test",
    title: "La pirámide de tests: unit, integración y e2e",
    description:
      "Por qué los tests se organizan en niveles: unitarios, de integración y end-to-end. El trade-off velocidad/confianza/coste, qué cubrir en cada nivel y por qué el cono de helado es un antipatrón.",
    href: "tutorials/tipos-de-test.html",
    categories: ["testing"],
    topic: "Testing",
    tags: ["Pirámide", "Integración", "E2E"],
    level: "Intermedio",
    minutes: 14,
    icon: "code",
    status: "published",
    date: "2026-06-26",
  },
  {
    slug: "tdd-ciclo",
    title: "El ciclo TDD: rojo, verde, refactor",
    description:
      "Qué es TDD y por qué se escribe el test antes que el código: el ritmo rojo-verde-refactor, los pasos pequeños (baby steps) y qué te da de verdad (diseño emergente y red de seguridad), con un ejemplo en PHP.",
    href: "tutorials/tdd-ciclo.html",
    categories: ["testing"],
    topic: "Testing",
    tags: ["TDD", "Red-Green-Refactor", "PHPUnit"],
    level: "Intermedio",
    minutes: 14,
    icon: "code",
    status: "published",
    date: "2026-06-26",
  },
  {
    slug: "owasp",
    title: "OWASP imprescindible: inyección, XSS y CSRF",
    description:
      "Las vulnerabilidades web más comunes y su raíz común (confiar en la entrada): inyección SQL y consultas preparadas, XSS y el escapado de salida, CSRF con token y SameSite, más los principios que cubren el resto del Top 10.",
    href: "tutorials/owasp.html",
    categories: ["seguridad"],
    topic: "Seguridad de fundamentos",
    tags: ["OWASP", "XSS", "CSRF"],
    level: "Intermedio",
    minutes: 16,
    icon: "shield",
    status: "published",
    date: "2026-06-22",
  },
  {
    slug: "autenticacion",
    title: "Autenticación: sesiones, JWT y OAuth",
    description:
      "Autenticar vs autorizar, las sesiones con cookie (estado en el servidor), el JWT autocontenido y su pega de revocación, y qué resuelve de verdad OAuth 2 / OpenID Connect. Cómo elegir según tu caso.",
    href: "tutorials/autenticacion.html",
    categories: ["seguridad"],
    topic: "Seguridad de fundamentos",
    tags: ["Sesiones", "JWT", "OAuth"],
    level: "Intermedio",
    minutes: 16,
    icon: "shield",
    status: "published",
    date: "2026-06-22",
  },
  {
    slug: "hashing-vs-cifrado",
    title: "Hashing vs cifrado: cómo se guardan las contraseñas",
    description:
      "La diferencia entre cifrar (reversible) y hashear (de un solo sentido), por qué las contraseñas se hashean y no se cifran, qué es la sal, por qué MD5/SHA no valen y cómo usar bcrypt o argon2 en PHP.",
    href: "tutorials/hashing-vs-cifrado.html",
    categories: ["seguridad"],
    topic: "Seguridad de fundamentos",
    tags: ["Hashing", "bcrypt", "argon2"],
    level: "Intermedio",
    minutes: 14,
    icon: "shield",
    status: "published",
    date: "2026-06-22",
  },
  {
    slug: "cap-consistencia",
    title: "CAP y consistencia eventual",
    description:
      "El teorema CAP sin misticismo: como las particiones de red ocurren, la elección real es consistencia vs disponibilidad. Qué promete la consistencia eventual, cómo resolver conflictos y cómo decidir por dato (quórums, PACELC).",
    href: "tutorials/cap-consistencia.html",
    categories: ["distribuidos"],
    topic: "Sistemas distribuidos",
    tags: ["CAP", "Consistencia", "Quórum"],
    level: "Avanzado",
    minutes: 15,
    icon: "signal",
    status: "published",
    date: "2026-06-22",
  },
  {
    slug: "idempotencia",
    title: "Idempotencia y entrega at-least-once",
    description:
      "Por qué en cuanto hay red los reintentos duplican, qué es una operación idempotente, las garantías de entrega (at-most/at-least/exactly-once), la clave de idempotencia y cómo deduplicar con una restricción única atómica.",
    href: "tutorials/idempotencia.html",
    categories: ["distribuidos", "mensajeria"],
    topic: "Sistemas distribuidos",
    tags: ["Idempotencia", "at-least-once", "Reintentos"],
    level: "Avanzado",
    minutes: 15,
    icon: "signal",
    status: "published",
    date: "2026-06-22",
  },
  {
    slug: "jerga",
    title: "La jerga del desarrollo, traducida",
    description:
      "Un glosario para entender a tu equipo: parsear, runtime, deploy y rollback; bug, edge case, race condition y memory leak; merge, rebase, PR y deuda técnica; payload, endpoint, idempotente y latencia; y la cultura (yak shaving, bikeshedding, rubber duck).",
    href: "tutorials/jerga.html",
    categories: ["cultura"],
    topic: "Cultura dev",
    tags: ["Glosario", "Vocabulario", "Cultura"],
    level: "Principiante",
    minutes: 14,
    icon: "code",
    status: "published",
    date: "2026-06-22",
  },
  {
    slug: "extensiones-php",
    title: "Extensiones de PHP: qué son y cuáles importan",
    description:
      "Qué es una extensión (un módulo en C que enchufa al motor), cómo se carga, la diferencia entre las del core y las de PECL, cómo ver las activas con php -m y el puñado que necesitas de verdad en producción.",
    href: "tutorials/extensiones-php.html",
    categories: ["php", "runtime"],
    topic: "PHP por dentro",
    tags: ["Extensiones", "PECL", "php.ini"],
    level: "Intermedio",
    minutes: 13,
    icon: "code",
    status: "published",
    date: "2026-06-22",
  },
  {
    slug: "php-fpm",
    title: "SAPIs y PHP-FPM a fondo",
    description:
      "Qué es un SAPI, en qué se diferencian CLI, mod_php, CGI y FPM, cómo FastCGI reutiliza procesos vivos, los modos de los pools (static/dynamic/ondemand), cómo dimensionar max_children y por qué PHP es shared-nothing.",
    href: "tutorials/php-fpm.html",
    categories: ["php", "runtime"],
    topic: "PHP por dentro",
    tags: ["PHP-FPM", "FastCGI", "Pools"],
    level: "Avanzado",
    minutes: 16,
    icon: "bolt",
    status: "published",
    date: "2026-06-22",
  },
  {
    slug: "memoria-php",
    title: "Cómo gestiona la memoria PHP",
    description:
      "El gestor de Zend y la arena por request, qué es memory_limit de verdad, los zvals y el refcounting, copy-on-write y el recolector de ciclos. Por qué liberar memoria en PHP es casi gratis.",
    href: "tutorials/memoria-php.html",
    categories: ["php", "runtime"],
    topic: "PHP por dentro",
    tags: ["Memoria", "Refcount", "Copy-on-write"],
    level: "Avanzado",
    minutes: 16,
    icon: "code",
    status: "published",
    date: "2026-06-22",
  },
  {
    slug: "workers-php",
    title: "Workers y modelos de ejecución en PHP",
    description:
      "Los dos sentidos de worker (los de FPM y los de cola), cómo se mantienen vivos con supervisor, el modelo long-running de Swoole y RoadRunner y por qué un worker que no muere se reinicia cada N jobs.",
    href: "tutorials/workers-php.html",
    categories: ["php", "runtime"],
    topic: "PHP por dentro",
    tags: ["Workers", "Colas", "Swoole"],
    level: "Avanzado",
    minutes: 15,
    icon: "bolt",
    status: "published",
    date: "2026-06-22",
  },
  {
    slug: "redis-a-fondo",
    title: "Redis a fondo: estructuras de datos en memoria",
    description:
      "Redis como servidor de estructuras de datos, no solo caché: strings y contadores, listas, sets y sorted sets, hashes, y los especiales (bitmaps, HyperLogLog, streams). TTL, nombrado de claves, atomicidad y persistencia RDB vs AOF.",
    href: "tutorials/redis-a-fondo.html",
    categories: ["infra", "bbdd"],
    topic: "Infraestructura",
    tags: ["Redis", "Estructuras", "Sorted sets"],
    level: "Intermedio",
    minutes: 17,
    icon: "database",
    status: "published",
    date: "2026-06-22",
  },
  {
    slug: "tcp-ip",
    title: "TCP/IP: el cartero fiable de internet",
    description:
      "Por qué TCP entrega datos en orden y sin pérdidas sobre una red que pierde, desordena y duplica paquetes: el handshake de tres pasos, qué identifican IP y puerto, el control de flujo por ventanas y las causas reales de que una conexión se quede colgada.",
    href: "tutorials/tcp-ip.html",
    categories: ["redes"],
    topic: "Cómo viaja un dato",
    tags: ["TCP", "IP", "Handshake"],
    level: "Avanzado",
    minutes: 15,
    icon: "signal",
    status: "published",
    date: "2026-06-21",
  },
  {
    slug: "http-a-fondo",
    title: "HTTP a fondo: métodos, estados y caché",
    description:
      "El protocolo de texto que mueve la web: anatomía de petición y respuesta, qué método usar y cuándo, los códigos de estado que de verdad importan, cómo funciona la caché de cabeceras y por qué HTTP no tiene estado (cookies vs tokens).",
    href: "tutorials/http-a-fondo.html",
    categories: ["redes"],
    topic: "Cómo viaja un dato",
    tags: ["HTTP", "Métodos", "Caché"],
    level: "Intermedio",
    minutes: 16,
    icon: "signal",
    status: "published",
    date: "2026-06-21",
  },
  {
    slug: "url-a-fondo",
    popular: true,
    title: "Qué pasa al escribir una URL",
    description:
      "El viaje completo de pulsar Enter a ver la página: anatomía de una URL, resolución DNS, el handshake de TCP, el cifrado de TLS y la petición HTTP final, con los errores típicos en cada eslabón de la cadena.",
    href: "tutorials/url-a-fondo.html",
    categories: ["redes"],
    topic: "Cómo viaja un dato",
    tags: ["DNS", "TLS", "HTTP"],
    level: "Intermedio",
    minutes: 14,
    icon: "signal",
    status: "published",
    date: "2026-06-21",
  },
  {
    slug: "memoria",
    title: "Memoria: stack, heap, virtual y caché",
    description:
      "La diferencia entre stack y heap, qué es la memoria virtual y por qué cada proceso cree tener la RAM para él solo, qué es la caché de CPU y la localidad de referencia, y cómo se nota en PHP (memory_limit, copy-on-write).",
    href: "tutorials/memoria.html",
    categories: ["sistemas"],
    topic: "El sistema por debajo",
    tags: ["Stack", "Heap", "Caché"],
    level: "Intermedio",
    minutes: 15,
    icon: "code",
    status: "published",
    date: "2026-06-21",
  },
  {
    slug: "async-event-loop",
    title: "Async y el event loop",
    description:
      "Por qué un hilo por conexión no escala, qué es el event loop, qué significa I/O no bloqueante, cuándo el async brilla y cuándo bloquear el loop lo arruina, y dónde encaja PHP entre FPM síncrono y Swoole/ReactPHP.",
    href: "tutorials/async-event-loop.html",
    categories: ["sistemas"],
    topic: "El sistema por debajo",
    tags: ["Async", "Event loop", "Swoole"],
    level: "Avanzado",
    minutes: 14,
    icon: "code",
    status: "published",
    date: "2026-06-21",
  },
  {
    slug: "concurrencia",
    popular: true,
    title: "Concurrencia: el bug que solo pasa en prod",
    description:
      "Race conditions explicadas con un ejemplo de stock, qué es una sección crítica y cómo la protege un mutex, qué es una operación atómica, cómo aparecen estas carreras en PHP vía la base de datos y qué es un deadlock.",
    href: "tutorials/concurrencia.html",
    categories: ["sistemas"],
    topic: "El sistema por debajo",
    tags: ["Race condition", "Mutex", "Deadlock"],
    level: "Avanzado",
    minutes: 15,
    icon: "code",
    status: "published",
    date: "2026-06-21",
  },
  {
    slug: "procesos-hilos",
    title: "Procesos vs hilos: qué comparten y qué no",
    description:
      "Qué es un proceso y qué es un hilo, qué memoria comparten y cuál está aislada, por qué PHP-FPM es multiproceso y no multihilo, y cuánto cuesta crear y conmutar entre unos y otros.",
    href: "tutorials/procesos-hilos.html",
    categories: ["sistemas"],
    topic: "El sistema por debajo",
    tags: ["Procesos", "Hilos", "PHP-FPM"],
    level: "Intermedio",
    minutes: 14,
    icon: "code",
    status: "published",
    date: "2026-06-21",
  },
  {
    slug: "modelado-relacional",
    title: "Modelado relacional: normalizar sin dogma",
    description:
      "Claves primarias y foráneas, relaciones uno a muchos y muchos a muchos, normalización de la 1FN a la 3FN explicada sin dogma y cuándo desnormalizar a propósito.",
    href: "tutorials/modelado-relacional.html",
    categories: ["bbdd"],
    topic: "Bases de datos",
    tags: ["Normalización", "Claves", "Relaciones"],
    level: "Intermedio",
    minutes: 14,
    icon: "database",
    status: "published",
    date: "2026-06-21",
  },
  {
    slug: "transacciones-acid",
    title: "Transacciones y ACID: todo o nada",
    description:
      "Qué garantiza una transacción (ACID), cómo deshacer un cambio a medias con ROLLBACK, los niveles de aislamiento, las lecturas sucias, no repetibles y fantasma, y por qué aparecen los deadlocks.",
    href: "tutorials/transacciones-acid.html",
    categories: ["bbdd"],
    topic: "Bases de datos",
    tags: ["ACID", "Transacciones", "Aislamiento"],
    level: "Avanzado",
    minutes: 16,
    icon: "database",
    status: "published",
    date: "2026-06-21",
  },
  {
    slug: "indices-btree",
    popular: true,
    title: "Índices y B-tree: por qué tu query es lenta",
    description:
      "Por qué una consulta sin índice lee la tabla entera, cómo un B-tree encuentra una fila en pocos saltos, cómo leer un EXPLAIN, el orden de columnas en índices compuestos y cuándo un índice no se usa.",
    href: "tutorials/indices-btree.html",
    categories: ["bbdd"],
    topic: "Bases de datos",
    tags: ["Índices", "B-tree", "EXPLAIN"],
    level: "Intermedio",
    minutes: 15,
    icon: "database",
    status: "published",
    date: "2026-06-21",
  },
  {
    slug: "hashing",
    title: "Hashing: cómo un hashmap busca en O(1)",
    description:
      "Qué hace una función hash, cómo convierte una clave en una posición, qué son las colisiones y cómo se resuelven, el factor de carga y el rehashing, y por qué un hashmap es O(1) de media pero O(n) en el peor caso.",
    href: "tutorials/hashing.html",
    categories: ["algoritmos"],
    topic: "Fundamentos",
    tags: ["Hashing", "Hashmap", "Colisiones"],
    level: "Intermedio",
    minutes: 14,
    icon: "code",
    status: "published",
    date: "2026-06-21",
  },
  {
    slug: "estructuras-datos",
    title: "Estructuras de datos: cuál usar y cuándo",
    description:
      "Array, lista enlazada, hashmap, set, árbol y grafo: qué hace barato y qué caro cada uno, cómo elegir por la operación que domina y por qué el array de PHP es un mapa ordenado.",
    href: "tutorials/estructuras-datos.html",
    categories: ["algoritmos"],
    topic: "Fundamentos",
    tags: ["Estructuras", "Hashmap", "Árboles"],
    level: "Intermedio",
    minutes: 15,
    icon: "code",
    status: "published",
    date: "2026-06-21",
  },
  {
    slug: "big-o",
    popular: true,
    title: "Big-O sin matemáticas: cómo saber si tu código escala",
    description:
      "Qué mide Big-O (cómo crece el coste, no los segundos), las clases que verás en la práctica (O(1), O(log n), O(n), O(n log n), O(n²)) y cómo cazar el O(n²) escondido que mata el rendimiento.",
    href: "tutorials/big-o.html",
    categories: ["algoritmos"],
    topic: "Fundamentos",
    tags: ["Big-O", "Complejidad", "Rendimiento"],
    level: "Intermedio",
    minutes: 14,
    icon: "signal",
    status: "published",
    date: "2026-06-21",
  },
  {
    slug: "numeros-flotantes",
    title: "Números: enteros, complemento a dos y coma flotante",
    description:
      "Por qué un entero no es infinito, cómo se guardan los negativos, qué es el overflow y por qué 0.1 + 0.2 no da 0.3: la coma flotante IEEE-754 y por qué el dinero nunca va en float.",
    href: "tutorials/numeros-flotantes.html",
    categories: ["representacion"],
    topic: "Fundamentos",
    tags: ["Enteros", "IEEE-754", "Overflow"],
    level: "Intermedio",
    minutes: 15,
    icon: "code",
    status: "published",
    date: "2026-06-21",
  },
  {
    slug: "texto-unicode",
    title: "Texto: de ASCII a Unicode y UTF-8",
    description:
      "Por qué un byte se queda corto para el texto, qué resuelve Unicode separando el carácter de sus bytes, cómo UTF-8 lo codifica en 1 a 4 bytes y por qué se rompen acentos y emojis.",
    href: "tutorials/texto-unicode.html",
    categories: ["representacion"],
    topic: "Fundamentos",
    tags: ["Unicode", "UTF-8", "Encoding"],
    level: "Intermedio",
    minutes: 14,
    icon: "code",
    status: "published",
    date: "2026-06-21",
  },
  {
    slug: "bits-y-bytes",
    title: "Bits y bytes: cómo cuenta de verdad un ordenador",
    description:
      "Qué es un bit, por qué ocho forman un byte, cómo se cuenta en binario y hexadecimal, y las operaciones bit a bit (AND, OR, XOR, shifts) detrás de máscaras y permisos.",
    href: "tutorials/bits-y-bytes.html",
    categories: ["representacion"],
    topic: "Fundamentos",
    tags: ["Binario", "Hexadecimal", "Bitwise"],
    level: "Intermedio",
    minutes: 13,
    icon: "code",
    status: "published",
    date: "2026-06-21",
  },
  {
    slug: "rabbitmq",
    title: "RabbitMQ a fondo: exchanges, colas y durabilidad",
    description:
      "Cómo enruta de verdad (exchanges y bindings), las propiedades de las colas, qué hace falta para no perder mensajes (durable + persistente + confirms), acks, DLX y los tipos de cola: classic, quorum y streams.",
    href: "tutorials/rabbitmq.html",
    categories: ["infra", "mensajeria"],
    topic: "Mensajería",
    tags: ["RabbitMQ", "AMQP", "Colas"],
    level: "Avanzado",
    minutes: 18,
    icon: "signal",
    status: "published",
    date: "2026-06-21",
  },
  {
    slug: "inyeccion-dependencias",
    title: "Inyección de dependencias en PHP",
    description:
      "Por qué una clase no debe fabricar sus colaboradores: desacoplar con constructor e interfaces, el contenedor y cómo todo esto hace tus tests triviales.",
    href: "tutorials/inyeccion-dependencias.html",
    categories: ["php", "arquitectura"],
    topic: "PHP",
    tags: ["PHP", "SOLID", "Testing"],
    level: "Intermedio",
    minutes: 16,
    icon: "code",
    status: "published",
    date: "2026-06-21",
  },
  {
    slug: "opcache",
    popular: true,
    title: "OPcache: cómo PHP deja de releer tu código",
    description:
      "Qué es, cómo funciona la caché de opcodes en memoria compartida, cómo configurarlo bien y los errores típicos que matan su efecto.",
    href: "tutorials/opcache.html",
    categories: ["php", "rendimiento"],
    topic: "PHP",
    tags: ["PHP", "Bytecode", "JIT"],
    level: "Intermedio",
    minutes: 15,
    icon: "bolt",
    status: "published",
    date: "2026-06-21",
  },
  {
    slug: "preload",
    title: "Preload: precargar clases al arrancar PHP",
    description:
      "El paso siguiente a OPcache: dejar las clases del framework cargadas y enlazadas en memoria desde el arranque, sin pasar por el autoload. Cómo funciona, cómo se configura, su gran pega (congela el código) y cómo lo dan Symfony y Laravel.",
    href: "tutorials/preload.html",
    categories: ["php", "rendimiento"],
    topic: "PHP",
    tags: ["Preload", "OPcache", "Rendimiento"],
    level: "Avanzado",
    minutes: 12,
    icon: "signal",
    status: "published",
    date: "2026-06-22",
  },
  {
    slug: "redis-cache",
    title: "Redis como caché de aplicación",
    description:
      "El patrón cache-aside paso a paso, por qué el TTL no es opcional, cómo invalidar sin carreras (borrar mejor que reescribir) y los tres fallos clásicos (penetration, avalanche, breakdown) más el cache stampede y su lock.",
    href: "tutorials/redis-cache.html",
    categories: ["infra", "rendimiento"],
    topic: "Infraestructura",
    tags: ["Redis", "Caché", "TTL"],
    level: "Intermedio",
    minutes: 15,
    icon: "database",
    status: "published",
    date: "2026-06-22",
  },
];
