/* ============================================================
   Exámenes por curso
   ------------------------------------------------------------
   Cada clave es el slug de un curso de MENTORAI_COURSES.
   La nota de corte por defecto es ceil(preguntas × 0.7).

   Estructura por pregunta:
     q  enunciado
     o  array de 4 opciones
     a  índice (0-based) de la opción correcta
   ============================================================ */

window.MENTORAI_QUIZZES = {

  /* -------- Git (10) -------- */
  "git": { questions: [
    { q: "¿Qué zona de git almacena los cambios que has marcado para incluir en el próximo commit?",
      o: ["Working directory", "Staging area / índice", "Repositorio local", "Repositorio remoto"], a: 1,
      w: "El staging area es la zona intermedia donde `git add` deja los cambios. Existe justo para que puedas elegir qué parte de tu trabajo entra en el commit y qué parte se queda fuera.",
      lesson: "git-comandos-esenciales" },
    { q: "¿Qué hace `git stash`?",
      o: ["Elimina los cambios sin commiteados permanentemente", "Guarda temporalmente los cambios sin commitear y limpia el working directory", "Crea un commit temporal en la rama actual", "Sube los cambios al remoto sin hacer commit"], a: 1,
      w: "Es el cajón para lo que tienes a medias: aparta los cambios y te deja el directorio limpio para cambiar de rama. Se recuperan con `git stash pop`, y no tocan el historial ni el remoto.",
      lesson: "git-comandos-esenciales" },
    { q: "¿Cuál es la diferencia entre `git fetch` y `git pull`?",
      o: ["Son equivalentes, hacen lo mismo", "`fetch` descarga cambios del remoto sin integrarlos; `pull` descarga y los integra", "`fetch` es para ramas remotas y `pull` para locales", "`pull` no modifica el working directory pero `fetch` sí"], a: 1,
      w: "`pull` es literalmente `fetch` + `merge`. Hacer `fetch` primero te deja mirar qué ha cambiado antes de integrarlo, que es justo lo que quieres cuando no te fías del estado del remoto.",
      lesson: "git-comandos-esenciales" },
    { q: "¿Qué hace `git reset --soft HEAD~1`?",
      o: ["Deshace el último commit descartando los cambios del working directory", "Deshace el último commit dejando los cambios en staging", "Deshace el último commit dejando los cambios en working directory sin staging", "Elimina el último commit del historial de forma permanente"], a: 1,
      w: "Los tres modos se distinguen por hasta dónde retroceden: `--soft` deja los cambios en staging, `--mixed` (el de por defecto) los deja en el working directory, y `--hard` los descarta. Es el comando para rehacer el último commit.",
      lesson: "git-deshacer" },
    { q: "¿Cuál es la regla de oro del rebase?",
      o: ["Siempre usar rebase en lugar de merge para mantener el historial limpio", "Nunca hacer rebase de commits que ya han sido compartidos con otros", "Hacer rebase solo en la rama principal", "Usar rebase solo para el último commit"], a: 1,
      w: "El rebase reescribe commits, o sea que les cambia el hash. Si alguien ya tenía los originales, su historial y el tuyo dejan de casar y el siguiente pull es un problema. Reescribe solo lo que aún no ha salido de tu máquina.",
      lesson: "git-ramas-y-flujo" },
    { q: "¿Qué hace `git reflog`?",
      o: ["Muestra el log de commits del remoto", "Muestra un registro de todos los movimientos de HEAD, permitiendo recuperar commits perdidos", "Muestra los ficheros modificados en cada commit", "Muestra las diferencias entre ramas"], a: 1,
      w: "Es la red de seguridad de git: registra cada movimiento de HEAD, incluso los de commits que ya no cuelgan de ninguna rama. Tras un `reset --hard` desafortunado, aquí está el hash para volver.",
      lesson: "git-deshacer" },
    { q: "¿Qué diferencia hay entre `git restore <fichero>` y `git restore --staged <fichero>`?",
      o: ["No hay diferencia, ambos hacen lo mismo", "El primero descarta cambios del working directory; el segundo los saca del staging sin borrarlos", "El primero actúa sobre staged y el segundo sobre working directory", "Ambos eliminan el fichero del repositorio"], a: 1,
      w: "Sin `--staged` descartas trabajo, y eso no se recupera. Con `--staged` solo deshaces el `git add`: los cambios siguen ahí, solo que fuera del próximo commit.",
      lesson: "git-deshacer" },
    { q: "¿Cuándo usarías `git revert` en lugar de `git reset`?",
      o: ["Cuando quieres deshacer varios commits a la vez", "Cuando quieres deshacer un commit ya empujado al remoto sin reescribir la historia", "Cuando el commit tiene conflictos", "Cuando trabajas solo y no hay remoto"], a: 1,
      w: "`revert` no borra: añade un commit nuevo que aplica los cambios al revés. Por eso es el seguro para lo ya compartido, mientras que `reset` reescribe y solo vale para lo que aún es tuyo.",
      lesson: "git-deshacer" },
    { q: "En un merge con conflicto, ¿qué muestra la sección `<<<<<<< HEAD`?",
      o: ["El inicio del fichero en conflicto", "El contenido de tu rama actual", "El contenido de la rama que estás mergeando", "El ancestro común de ambas ramas"], a: 1,
      w: "El bloque va de `<<<<<<< HEAD` a `=======` con lo tuyo, y de ahí a `>>>>>>>` con lo que entra. Resolver no es elegir un lado a ciegas: es escribir la versión correcta y borrar los marcadores.",
      lesson: "git-ramas-y-flujo" },
    { q: "¿Qué es un pull request?",
      o: ["Un comando de git para traer cambios del remoto", "Una petición para que otros revisen y fusionen tu rama antes de integrarla", "Una forma de hacer fetch y pull simultáneamente", "Un tipo especial de merge que no crea commit de merge"], a: 1,
      w: "No es de git, es de la plataforma (GitHub, GitLab…). Aporta lo que git no da por sí solo: un sitio donde revisar, comentar y pasar CI antes de que el código entre en la rama principal.",
      lesson: "git-ramas-y-flujo" },
  ]},

  /* -------- OOP (12) -------- */
  "oop": { questions: [
    { q: "¿Qué es la encapsulación en OOP?",
      o: ["Crear clases con muchos métodos públicos para facilitar el acceso", "Ocultar el estado interno de un objeto y exponer solo lo necesario a través de una interfaz controlada", "Hacer que todos los atributos sean privados sin ningún método de acceso", "Heredar comportamiento de múltiples clases padre"], a: 1 },
    { q: "¿Cuál es la diferencia clave entre una clase abstracta y una interfaz?",
      o: ["Una clase abstracta no puede tener métodos implementados; una interfaz sí", "Una interfaz define un contrato sin implementación; una clase abstracta puede tener implementación parcial y estado", "Una clase abstracta puede instanciarse directamente; una interfaz no", "No hay diferencia práctica en PHP moderno"], a: 1 },
    { q: "¿Qué ocurre si una clase hija no implementa todos los métodos abstractos de su padre?",
      o: ["PHP lanza un aviso pero la clase funciona", "PHP lanza un error fatal", "La clase hija queda también abstracta automáticamente", "Los métodos abstractos sin implementar se ignoran"], a: 1 },
    { q: "¿Cuál es el problema de las jerarquías de herencia profundas?",
      o: ["PHP no soporta más de 3 niveles de herencia", "Cada nivel añade acoplamiento: un cambio en la base puede romper toda la cadena de subclases", "Consumen demasiada memoria en tiempo de ejecución", "No se puede usar polimorfismo con ellas"], a: 1 },
    { q: "¿Qué ventaja tiene preferir composición sobre herencia?",
      o: ["La composición es siempre más rápida en tiempo de ejecución", "Permite combinar comportamientos de forma flexible sin crear jerarquías frágiles", "La composición permite reutilizar código sin crear nuevas clases", "Herencia y composición tienen exactamente las mismas ventajas"], a: 1 },
    { q: "¿Qué palabra clave impide que una clase pueda ser extendida en PHP?",
      o: ["abstract", "sealed", "final", "readonly"], a: 2 },
    { q: "¿Para qué sirve `parent::__construct()` en una clase hija?",
      o: ["Para llamar al constructor del abuelo en una jerarquía de 3 niveles", "Para invocar el constructor de la clase padre y ejecutar su inicialización", "Para copiar las propiedades del padre a la hija automáticamente", "Es obligatorio en todos los constructores de clases hija"], a: 1 },
    { q: "¿Qué es el polimorfismo?",
      o: ["La capacidad de una clase de tener múltiples constructores", "La capacidad de objetos de distinto tipo de responder al mismo mensaje de manera diferente", "La capacidad de una clase de implementar múltiples interfaces", "La capacidad de cambiar el tipo de una variable en tiempo de ejecución"], a: 1 },
    { q: "¿Qué garantiza un type hint de interfaz en un parámetro?",
      o: ["Que el objeto es una instancia de esa interfaz concreta", "Que el objeto implementa todos los métodos definidos en esa interfaz", "Que el objeto hereda de una clase que implementa la interfaz", "Que la función solo acepta objetos de una única clase concreta"], a: 1 },
    { q: "¿Cuándo usarías un trait en PHP?",
      o: ["Como sustituto de la herencia para reutilizar código entre clases sin relación jerárquica", "Siempre que quieras definir un contrato que varias clases deben cumplir", "Para crear objetos con comportamiento configurable en tiempo de ejecución", "Solo cuando una clase necesita heredar de más de una clase padre"], a: 0 },
    { q: "¿Qué son los enums en PHP 8.1?",
      o: ["Una forma de crear constantes de clase con valores numéricos", "Un tipo especial que define un conjunto fijo de valores válidos para un tipo", "Una alternativa a los traits para compartir comportamiento", "Una forma de crear clases con propiedades de solo lectura"], a: 1 },
    { q: "¿Cuál es el principal beneficio de las clases `readonly` en PHP 8.2?",
      o: ["Que sus métodos no pueden ser sobreescritos por subclases", "Que sus propiedades solo pueden asignarse en el constructor, garantizando inmutabilidad", "Que son más rápidas porque PHP las optimiza en compilación", "Que no necesitan constructor porque PHP las inicializa automáticamente"], a: 1 },
  ]},

  /* -------- SOLID (15) -------- */
  "solid": { questions: [
    { q: "¿Qué significa que una clase tenga 'una sola razón para cambiar' (SRP)?",
      o: ["Que solo tiene un método público", "Que solo hay un actor o stakeholder que puede obligarla a modificarse", "Que solo tiene una dependencia externa", "Que no puede ser heredada por más de una subclase"], a: 1 },
    { q: "Una clase que calcula facturas, las persiste en BD y las imprime en PDF viola:",
      o: ["El principio Open/Closed", "El principio de Responsabilidad Única", "El principio de Liskov", "El principio de Inversión de Dependencias"], a: 1 },
    { q: "El principio Open/Closed dice que el software debe estar:",
      o: ["Abierto para ser testeado y cerrado para modificarse en producción", "Abierto para extensión y cerrado para modificación", "Abierto para herencia y cerrado para composición", "Abierto al equipo y cerrado a cambios externos"], a: 1 },
    { q: "¿Qué mecanismo permite cumplir Open/Closed añadiendo comportamiento nuevo?",
      o: ["El patrón Singleton", "El polimorfismo con interfaces o el patrón Strategy", "El patrón Factory", "El patrón Observer"], a: 1 },
    { q: "¿Qué viola el principio de Sustitución de Liskov?",
      o: ["Una subclase que añade nuevos métodos no existentes en el padre", "Una subclase que lanza excepciones en métodos heredados que el padre nunca lanzaría", "Una subclase que sobreescribe métodos del padre con la misma firma", "Una subclase que extiende una clase abstracta"], a: 1 },
    { q: "El ejemplo clásico de violación de LSP es:",
      o: ["Un Perro que extiende de Animal y sobreescribe `hablar()`", "Un Cuadrado que extiende de Rectángulo y rompe el invariante de sus dimensiones", "Un Círculo que implementa la interfaz Forma con el método `area()`", "Un Manager que extiende de Employee y añade métodos de gestión"], a: 1 },
    { q: "El principio de Segregación de Interfaces (ISP) recomienda:",
      o: ["Crear interfaces grandes y completas para agrupar toda la funcionalidad relacionada", "Crear interfaces pequeñas y específicas para que los clientes no dependan de métodos que no usan", "Que cada clase implemente solo una interfaz", "Evitar las interfaces y usar clases abstractas"], a: 1 },
    { q: "Una interfaz `Dispositivo` con métodos `imprimir()`, `escanear()` y `faxear()` viola ISP porque:",
      o: ["Tiene demasiados métodos para ser útil", "Una impresora sin escáner ni fax se ve obligada a implementar métodos que no necesita", "Los métodos no siguen la convención de nombres correcta", "Una interfaz solo puede tener un método según ISP"], a: 1 },
    { q: "¿Qué invierte el principio de Inversión de Dependencias (DIP)?",
      o: ["El orden en que se llaman los métodos", "La dirección del acoplamiento: ambos módulos dependen de una abstracción, no el alto nivel del bajo nivel", "La jerarquía de herencia entre clases", "El orden de carga de dependencias en el contenedor"], a: 1 },
    { q: "¿A quién pertenece la abstracción (interfaz) según el DIP?",
      o: ["Al módulo de bajo nivel que la implementa", "Al módulo de alto nivel que la usa", "A un módulo compartido independiente de ambos", "Al framework de inyección de dependencias"], a: 1 },
    { q: "Si un servicio de dominio importa directamente un repositorio MySQL concreto, ¿qué viola?",
      o: ["El principio de Responsabilidad Única", "El principio de Inversión de Dependencias", "El principio de Segregación de Interfaces", "El principio Open/Closed"], a: 1 },
    { q: "¿Por qué los principios SOLID se refuerzan mutuamente?",
      o: ["Son independientes y no tienen relación entre sí", "OCP es difícil de cumplir sin ISP; DIP facilita OCP; LSP garantiza que los sustitutos de OCP sean válidos", "Solo SRP y DIP están relacionados", "Son aplicaciones del mismo principio con distinto nombre"], a: 1 },
    { q: "¿Cuándo NO tiene sentido aplicar todos los principios SOLID?",
      o: ["En proyectos que usan frameworks modernos", "En scripts sencillos o glue code donde la abstracción añadiría complejidad sin valor", "Cuando el equipo tiene menos de 5 personas", "SOLID siempre debe aplicarse independientemente del contexto"], a: 1 },
    { q: "¿Qué tienen en común Strategy y Observer con el principio OCP?",
      o: ["Los tres reducen la cantidad de clases necesarias", "Strategy y Observer son implementaciones concretas de OCP: añaden comportamiento sin modificar el código existente", "Los tres se basan en herencia en lugar de composición", "Los tres son obligatorios para cumplir SOLID"], a: 1 },
    { q: "En SOLID, 'cohesión' y 'acoplamiento' son:",
      o: ["Sinónimos que describen cuánto se relacionan las clases", "Cohesión mide lo que hay DENTRO de una clase; acoplamiento mide la dependencia de lo que hay FUERA", "Cohesión es negativa y acoplamiento positivo", "Cohesión se refiere a interfaces y acoplamiento a herencia"], a: 1 },
  ]},

  /* -------- Clean Code (12) -------- */
  "clean-code": { questions: [
    { q: "¿Por qué importa que el código sea fácil de leer?",
      o: ["Porque los compiladores lo procesan más rápido", "Porque el código se lee muchas más veces de las que se escribe, y la comprensión tiene un coste real", "Porque es un requisito de los estándares PSR", "Porque facilita la ofuscación en producción"], a: 1 },
    { q: "Un nombre como `$d` para una variable de días transcurridos es problemático porque:",
      o: ["Tiene demasiados pocos caracteres para que el linter lo detecte", "No revela la intención; obliga al lector a deducir su significado por el contexto", "Los nombres de variable no pueden ser de un solo carácter en PHP", "Viola la convención camelCase"], a: 1 },
    { q: "¿Qué es la 'regla del boy scout' aplicada al código?",
      o: ["Nunca modificar código que no está roto", "Dejar el código un poco mejor de como lo encontraste cada vez que lo tocas", "Siempre escribir tests antes de refactorizar", "Documentar todos los cambios que haces"], a: 1 },
    { q: "¿Cuál es el problema de las funciones con muchos argumentos?",
      o: ["Que PHP las ejecuta más lento", "Que son difíciles de llamar, de testear y revelan que la función probablemente hace demasiadas cosas", "Que violan el principio Open/Closed", "Solo son un problema si superan los 10 argumentos"], a: 1 },
    { q: "¿Qué es un 'flag argument' y por qué es problemático?",
      o: ["Un argumento booleano que cambia el comportamiento de la función, señalando que hace más de una cosa", "Un argumento obligatorio sin valor por defecto", "Un argumento que se usa solo en entornos de desarrollo", "Un argumento cuyo nombre contiene la palabra 'flag'"], a: 0 },
    { q: "¿Cuándo está justificado un comentario según clean code?",
      o: ["Siempre que la lógica sea compleja", "Cuando el WHY (la razón de fondo) no es deducible del código, no el WHAT (qué hace)", "Cuando el código tiene más de 10 líneas", "Solo en métodos públicos de la API pública"], a: 1 },
    { q: "'El comentario como disculpa' significa:",
      o: ["Pedir perdón al equipo por el tiempo que tardará en entender el código", "Que un comentario que explica código oscuro es un síntoma: lo correcto sería mejorar el código", "Que los comentarios deben incluir el nombre del autor", "Que los comentarios son siempre innecesarios"], a: 1 },
    { q: "¿Qué problema tiene devolver `null` desde un método?",
      o: ["PHP no permite devolver null si el tipo de retorno está declarado", "Obliga a todos los llamadores a comprobar null antes de usar el resultado, propagando la posibilidad de error", "El tipo null no existe en PHP moderno", "Solo es un problema en lenguajes con punteros"], a: 1 },
    { q: "¿Qué es el principio 'fail fast'?",
      o: ["Hacer que el sistema falle en producción lo antes posible para minimizar daños", "Validar las precondiciones al entrar en un método y lanzar excepciones cuanto antes, en lugar de propagar estado inválido", "Usar excepciones en lugar de valores de retorno en todos los casos", "Evitar el manejo de errores para que los fallos sean evidentes"], a: 1 },
    { q: "¿Cuál de estos es un ejemplo claro de 'code smell'?",
      o: ["Una clase con un único método público bien nombrado", "Un método de 200 líneas que hace 12 cosas distintas", "Una interfaz implementada por 3 clases diferentes", "Un archivo con 20 constantes de clase"], a: 1 },
    { q: "Refactorizar significa 'cambiar la forma sin cambiar el comportamiento'. ¿Qué implica esto?",
      o: ["Solo se pueden renombrar variables, no reestructurar la lógica", "El código refactorizado debe producir exactamente los mismos resultados que antes para los mismos inputs", "El comportamiento puede cambiar ligeramente si mejora el rendimiento", "Refactorizar no requiere tests porque el objetivo no es el comportamiento"], a: 1 },
    { q: "¿Por qué no se debe refactorizar sin tests?",
      o: ["Porque es un requisito de los estándares de código", "Porque sin tests no hay forma fiable de verificar que el comportamiento no cambió durante la refactorización", "Porque el compilador no puede optimizar código sin tests", "Porque los tests generan la documentación del código"], a: 1 },
  ]},

  /* -------- DI y contenedores (10) -------- */
  "di-contenedores": { questions: [
    { q: "¿Qué problema resuelve la inyección de dependencias?",
      o: ["Que las clases no tengan que instanciar sus propias dependencias, reduciendo el acoplamiento", "Que las clases se carguen más rápido en memoria", "Que las dependencias se compartan entre todos los objetos", "Que no sea necesario declarar el tipo de las propiedades"], a: 0 },
    { q: "¿Por qué la inyección por constructor es preferible a la inyección por setter?",
      o: ["Porque PHP la resuelve automáticamente sin configuración", "Porque garantiza que el objeto esté completamente inicializado al crearse, sin estados intermedios inválidos", "Porque los setters son más lentos en PHP", "Porque los constructores permiten inyectar más dependencias"], a: 1 },
    { q: "¿Cómo funciona el autowiring de un contenedor DI?",
      o: ["Lee un fichero de configuración XML con las dependencias de cada clase", "Usa reflexión para inspeccionar los type hints del constructor e instanciar automáticamente las dependencias", "Busca en un registro global qué implementación corresponde a cada interfaz", "Genera código en tiempo de compilación que se ejecuta en runtime"], a: 1 },
    { q: "¿Qué es el ciclo de vida 'shared/singleton' en un contenedor DI?",
      o: ["Que el contenedor crea una nueva instancia en cada petición", "Que el contenedor crea la instancia una sola vez y devuelve siempre la misma", "Que la instancia se comparte entre varios contenedores diferentes", "Que la instancia se destruye al final de cada método"], a: 1 },
    { q: "¿Qué es un 'lazy service' en el contexto de un contenedor DI?",
      o: ["Un servicio que solo se instancia cuando se accede a él por primera vez, no al inicializar el contenedor", "Un servicio que se carga desde un fichero de caché en disco", "Un servicio con pocas dependencias que se instancia rápidamente", "Un servicio compartido entre múltiples contenedores"], a: 0 },
    { q: "¿Por qué Symfony compila el contenedor DI?",
      o: ["Para verificar que todas las dependencias están correctamente configuradas", "Para generar código PHP optimizado que resuelve las dependencias sin reflexión en runtime", "Para crear la documentación de las dependencias del proyecto", "Para exportar el grafo de dependencias a un formato legible"], a: 1 },
    { q: "¿Qué riesgo introduce usar un contenedor en workers PHP long-running (Swoole/RoadRunner)?",
      o: ["Que el autowiring falla por la falta de petición HTTP", "Que los servicios con estado se comparten entre peticiones, pudiendo filtrar datos entre usuarios", "Que el contenedor se destruye al final de la primera petición", "Que el autowiring es más lento sin el ciclo de petición de FPM"], a: 1 },
    { q: "¿Qué es el 'service locator' y por qué se considera un antipatrón?",
      o: ["Es el nombre correcto del contenedor DI; no es un antipatrón", "Es obtener dependencias llamando directamente al contenedor desde dentro de una clase, ocultando las dependencias reales", "Es un patrón para localizar servicios en un sistema distribuido", "Es una alternativa válida a la inyección por constructor"], a: 1 },
    { q: "¿Qué detecta la comprobación de ciclos en un contenedor DI?",
      o: ["Que una clase depende de sí misma directa o indirectamente, lo que haría imposible construirla", "Que se están instanciando demasiados servicios en paralelo", "Que dos servicios tienen el mismo nombre en el contenedor", "Que hay dependencias que no se usan en ningún punto del código"], a: 0 },
    { q: "¿Qué diferencia hay entre DIP (principio) e inyección de dependencias (técnica)?",
      o: ["Son exactamente lo mismo con distinto nombre", "DIP dice que los módulos deben depender de abstracciones; la inyección de dependencias es la técnica para lograrlo", "La inyección de dependencias viola el DIP porque usa el contenedor como service locator", "DIP aplica a interfaces y la inyección de dependencias aplica a clases concretas"], a: 1 },
  ]},

  /* -------- SQL aplicado (12) -------- */
  "sql-aplicado": { questions: [
    { q: "¿Qué devuelve un INNER JOIN entre dos tablas?",
      o: ["Todos los registros de la tabla izquierda y los que coincidan de la derecha", "Solo los registros que tienen coincidencia en AMBAS tablas", "Todos los registros de ambas tablas combinados", "Los registros que no tienen coincidencia en ninguna de las dos tablas"], a: 1 },
    { q: "¿En qué caso usarías LEFT JOIN en lugar de INNER JOIN?",
      o: ["Cuando quieres que el resultado sea más rápido", "Cuando quieres incluir registros de la tabla izquierda aunque no tengan correspondencia en la derecha", "Cuando ambas tablas tienen el mismo número de registros", "Cuando quieres filtrar los NULL del resultado"], a: 1 },
    { q: "¿Cuál es la diferencia entre WHERE y HAVING?",
      o: ["WHERE filtra antes de agrupar; HAVING filtra después de agrupar sobre el resultado del GROUP BY", "Son equivalentes pero HAVING es más moderno", "WHERE se usa con SELECT y HAVING con UPDATE", "HAVING filtra columnas y WHERE filtra filas"], a: 0 },
    { q: "¿Qué devuelve `COUNT(*)` vs `COUNT(columna)`?",
      o: ["Son equivalentes, devuelven el mismo resultado", "`COUNT(*)` cuenta todas las filas; `COUNT(columna)` excluye los NULL de esa columna", "`COUNT(*)` es más lento porque recorre todos los campos", "`COUNT(columna)` devuelve el número de valores distintos"], a: 1 },
    { q: "¿Qué es una subconsulta correlacionada?",
      o: ["Una subconsulta que se ejecuta una sola vez y su resultado se usa en la consulta exterior", "Una subconsulta que referencia columnas de la consulta exterior y se evalúa una vez por cada fila", "Una subconsulta que usa un alias de la consulta exterior", "Una subconsulta que se define con WITH"], a: 1 },
    { q: "¿Qué ventaja aporta un CTE (WITH) sobre una subconsulta anidada equivalente?",
      o: ["Que los CTEs se ejecutan antes que el resto de la consulta, acelerándola siempre", "Que el CTE tiene nombre y puede referenciarse varias veces, mejorando la legibilidad y evitando repetición", "Que los CTEs permiten usar funciones que no se pueden usar en subconsultas", "Que los CTEs son siempre más eficientes que las subconsultas"], a: 1 },
    { q: "¿En qué se diferencian las window functions de GROUP BY?",
      o: ["Las window functions son una sintaxis alternativa para hacer lo mismo que GROUP BY", "Las window functions calculan un valor por fila sin reducir el número de filas del resultado", "GROUP BY siempre es más eficiente que las window functions", "Las window functions solo funcionan con funciones de agregación"], a: 1 },
    { q: "¿Qué hace `ROW_NUMBER() OVER (PARTITION BY departamento ORDER BY salario DESC)`?",
      o: ["Numera todas las filas del resultado de 1 a N", "Numera las filas dentro de cada departamento, reiniciando el contador, ordenando por salario descendente", "Devuelve el salario máximo de cada departamento", "Agrupa las filas por departamento y cuenta cuántas hay"], a: 1 },
    { q: "¿Cuál es el resultado de `LAG(precio, 1) OVER (ORDER BY fecha)`?",
      o: ["El valor de precio de la siguiente fila en el orden", "El valor de precio de la fila anterior en el orden por fecha", "La diferencia entre el precio actual y el anterior", "El precio promedio entre la fila actual y la anterior"], a: 1 },
    { q: "¿Para qué sirve el patrón 'top-N por grupo' con window functions?",
      o: ["Para ordenar un resultado por múltiples columnas a la vez", "Para obtener los N mejores registros dentro de cada categoría sin subconsultas complejas", "Para calcular promedios móviles sobre una ventana temporal", "Para eliminar duplicados manteniendo solo el primer registro de cada grupo"], a: 1 },
    { q: "¿Qué ocurre si en GROUP BY seleccionas una columna no agregada que no está en el GROUP BY?",
      o: ["MySQL selecciona un valor aleatorio de esa columna", "En modo estricto (ONLY_FULL_GROUP_BY) el motor devuelve un error", "PHP lanza una excepción al ejecutar la consulta", "La columna toma el valor de la primera fila del grupo siempre"], a: 1 },
    { q: "¿Cómo obtendrías los 3 empleados con mayor salario de cada departamento?",
      o: ["SELECT * FROM empleados ORDER BY salario DESC LIMIT 3", "Con ROW_NUMBER() OVER (PARTITION BY departamento ORDER BY salario DESC) filtrando WHERE rn <= 3", "SELECT departamento, MAX(salario) FROM empleados GROUP BY departamento LIMIT 3", "SELECT * FROM empleados WHERE salario IN (SELECT TOP 3 salario FROM empleados)"], a: 1 },
  ]},

  /* -------- APIs REST (12) -------- */
  "apis-rest": { questions: [
    { q: "En REST, ¿qué es un 'recurso'?",
      o: ["Un endpoint de la API", "Una entidad con identidad propia que puede ser representada y manipulada a través de la API", "Un método HTTP disponible en la API", "Un fichero almacenado en el servidor"], a: 1 },
    { q: "¿Qué significa que REST sea stateless?",
      o: ["Que el servidor no guarda ningún dato en base de datos", "Que cada petición contiene toda la información necesaria para procesarse, sin depender de sesiones en el servidor", "Que los clientes no pueden mantener sesiones de usuario", "Que la API no puede manejar transacciones de múltiples pasos"], a: 1 },
    { q: "¿Cuál es la diferencia entre PUT y PATCH?",
      o: ["PUT es idempotente y PATCH no lo es nunca", "PUT reemplaza el recurso completo; PATCH aplica una modificación parcial", "PUT crea recursos y PATCH los modifica", "No hay diferencia: ambos actualizan recursos de forma equivalente"], a: 1 },
    { q: "¿Qué código de estado HTTP corresponde a la creación exitosa de un recurso?",
      o: ["200 OK", "201 Created", "204 No Content", "202 Accepted"], a: 1 },
    { q: "¿Cuál es la diferencia entre un error 401 y un 403?",
      o: ["401 es 'recurso no encontrado' y 403 es 'método no permitido'", "401 significa 'no autenticado' (no sé quién eres); 403 significa 'no autorizado' (sé quién eres pero no tienes permiso)", "401 es para APIs y 403 para páginas web", "Son equivalentes; el código a usar depende del framework"], a: 1 },
    { q: "¿Por qué no se debe anidar recursos más de un nivel en las URLs REST?",
      o: ["Por limitaciones de los servidores HTTP modernos", "Porque las URLs muy anidadas acoplan el cliente a la estructura interna del dominio, haciéndolas frágiles", "Porque los proxies no soportan URLs con más de dos segmentos", "Es solo una recomendación estética sin implicaciones prácticas"], a: 1 },
    { q: "¿Qué ventaja tiene el cursor-based pagination sobre el offset-based pagination?",
      o: ["El cursor es más fácil de implementar en cualquier base de datos", "El cursor no falla si se insertan o eliminan registros entre peticiones y escala bien en tablas grandes", "El cursor permite saltar a cualquier página, mientras que el offset solo avanza", "El cursor-based es más lento pero más preciso"], a: 1 },
    { q: "¿Qué es el formato `problem+json` (RFC 9457)?",
      o: ["Una librería PHP para serializar excepciones como JSON", "Un estándar para representar errores de API HTTP con campos consistentes (type, title, status, detail)", "Un tipo de JWT con información de error codificada", "Una extensión de JSON Schema para validar respuestas de error"], a: 1 },
    { q: "¿Para qué sirve la cabecera `Idempotency-Key`?",
      o: ["Una clave de autenticación alternativa al JWT", "Un identificador único que el cliente envía para que el servidor detecte y deduplique peticiones repetidas", "Una clave de cifrado para peticiones con datos sensibles", "Un header para indicar la versión de la API que el cliente espera"], a: 1 },
    { q: "¿Cuándo es más apropiado usar gRPC que REST?",
      o: ["Cuando necesitas que la API sea accesible desde un navegador", "En comunicación interna máquina-a-máquina donde se prioriza el rendimiento y los contratos estrictos", "Cuando el cliente no soporta HTTP/2", "Siempre que necesites streaming bidireccional"], a: 1 },
    { q: "¿Cuál es el principal problema de GraphQL respecto a la caché HTTP?",
      o: ["GraphQL no permite usar caché en el cliente", "Al usar POST para todas las consultas, las respuestas no son cacheables por los proxies HTTP estándar", "GraphQL requiere cabeceras especiales que invalidan la caché", "Solo es un problema con clientes Apollo"], a: 1 },
    { q: "¿Qué significa el nivel 2 del modelo de madurez de Richardson?",
      o: ["Usar HATEOAS y enlaces en las respuestas", "Usar correctamente los verbos HTTP y los códigos de estado según su semántica", "Tener una única URL para todos los recursos con parámetros en el body", "Usar versioning en la URL como /v1/recursos"], a: 1 },
  ]},

  /* -------- Acceso a datos (12) -------- */
  "acceso-a-datos": { questions: [
    { q: "¿Qué es el 'desajuste de impedancia' entre OOP y bases de datos relacionales?",
      o: ["Que los ORMs son más lentos que el SQL nativo", "Que los objetos tienen herencia y relaciones de distinto tipo que las tablas y filas relacionales", "Que PHP no puede conectarse directamente a una base de datos sin un ORM", "Que las bases de datos no pueden almacenar objetos complejos"], a: 1 },
    { q: "¿En qué situación usarías SQL nativo sobre un ORM?",
      o: ["Siempre que necesites un SELECT", "En consultas complejas con window functions o CTEs que el ORM no expresa bien y requieren máximo rendimiento", "Solo cuando el ORM no soporta el motor de base de datos", "Nunca: el ORM siempre genera SQL equivalente al manual"], a: 1 },
    { q: "¿Cuál es la diferencia principal entre Active Record y Data Mapper?",
      o: ["Active Record es un patrón más moderno que reemplaza a Data Mapper", "En Active Record la entidad se persiste a sí misma; en Data Mapper la entidad es pura y un mapper externo gestiona la persistencia", "Data Mapper usa SQL nativo y Active Record usa un query builder", "Active Record es de Laravel y Data Mapper es de Symfony"], a: 1 },
    { q: "¿Qué ocurre al acceder a `$post->comments` en Eloquent sin eager loading?",
      o: ["Lanza una excepción porque la relación no está cargada", "Ejecuta una consulta SQL adicional para cargar los comentarios (lazy loading)", "Devuelve null si los comentarios no estaban en el resultado original", "Devuelve una colección vacía sin consultar la base de datos"], a: 1 },
    { q: "¿Qué es el problema N+1?",
      o: ["Que una consulta con N JOINs consume N+1 veces más memoria", "Que al iterar N elementos y acceder a una relación en cada iteración, se ejecutan N+1 consultas en total", "Que al paginarse con OFFSET N se ejecuta 1 consulta de más", "Que un índice compuesto tiene un coste de N+1 sobre la escritura"], a: 1 },
    { q: "¿Cómo soluciona el eager loading el problema N+1?",
      o: ["Añadiendo un índice a la columna de clave foránea", "Cargando todas las relaciones necesarias en 1-2 consultas antes de iterar, en lugar de una por elemento", "Usando transacciones para agrupar todas las consultas en una sola", "Cacheando las relaciones en Redis para evitar múltiples consultas a la BD"], a: 1 },
    { q: "¿Cuál es la regla de oro de las migraciones aplicadas en entornos compartidos?",
      o: ["Que deben revertirse antes de cada despliegue para garantizar un estado limpio", "Que son inmutables: una vez aplicada en equipo o producción no se modifica, se añade una nueva", "Que deben incluir siempre un método down() para poder revertirlas", "Que deben ejecutarse manualmente en producción, nunca automáticamente"], a: 1 },
    { q: "¿Qué diferencia hay entre revertir con `down()` y la estrategia 'roll forward'?",
      o: ["Son estrategias equivalentes para distintos entornos", "`down()` revierte el esquema; roll forward añade una nueva migración que corrige el error sin modificar la historia", "Roll forward es más lento pero preserva los datos existentes", "`down()` es la estrategia recomendada para producción por su seguridad"], a: 1 },
    { q: "¿Qué acumula el Unit of Work antes de llamar a `flush()`?",
      o: ["Las queries SQL para ejecutarlas en paralelo", "Los cambios detectados en las entidades gestionadas, para escribirlos todos juntos en una sola transacción", "Las entidades que deben eliminarse de la caché de primer nivel", "Las conexiones a base de datos que deben cerrarse al final del request"], a: 1 },
    { q: "¿Cuál es el riesgo de usar un ORM en workers PHP long-running?",
      o: ["Que el Unit of Work no funciona fuera del ciclo de petición HTTP", "Que la caché de entidades crece indefinidamente entre peticiones, causando fugas de memoria", "Que el ORM no puede usar pools de conexión en procesos persistentes", "Que las transacciones se cierran al final de cada petición automáticamente"], a: 1 },
    { q: "¿Por qué `flush()` no es lo mismo que `commit()`?",
      o: ["Son sinónimos en Doctrine; flush siempre inicia y cierra una transacción", "`flush()` escribe los cambios en la BD pero puede hacerse dentro de una transacción abierta; `commit()` la cierra", "`commit()` solo existe en PDO, no en el ORM", "`flush()` solo escribe en memoria; `commit()` los persiste en disco"], a: 1 },
    { q: "¿Qué problema introduce llamar a `flush()` dentro de un bucle?",
      o: ["El ORM ejecuta una transacción por iteración en lugar de una sola global", "El ORM duplica las entidades en la caché de primer nivel", "El bucle no termina hasta que todas las queries se resuelven", "Cada flush() dentro de un bucle crea una conexión nueva a la BD"], a: 0 },
  ]},

  /* -------- Docker (12) -------- */
  "docker": { questions: [
    { q: "¿Cuál es la diferencia fundamental entre una imagen y un contenedor Docker?",
      o: ["Son lo mismo pero en distintas fases del ciclo de despliegue", "La imagen es la plantilla inmutable; el contenedor es la instancia en ejecución creada a partir de la imagen", "La imagen es lo que se ejecuta; el contenedor es lo que se almacena en disco", "La imagen contiene el código y el contenedor las dependencias del sistema"], a: 1 },
    { q: "¿Por qué Docker no es lo mismo que una máquina virtual?",
      o: ["Porque Docker es más lento que una VM para cargas de trabajo intensivas", "Porque un contenedor comparte el kernel del sistema operativo anfitrión en lugar de virtualizarlo", "Porque Docker no puede ejecutar procesos en background", "Porque una VM puede usar más memoria que un contenedor"], a: 1 },
    { q: "¿Qué determina si Docker puede reutilizar la caché de una capa?",
      o: ["El tamaño de la imagen resultante", "Si esa capa ha cambiado respecto al build anterior (y si cambia, todas las capas siguientes deben reconstruirse)", "Qué capas se comparten entre imágenes en el mismo host", "El orden en que se descargan las capas del registry"], a: 1 },
    { q: "¿Por qué poner `COPY composer.json` y `RUN composer install` ANTES de `COPY . .`?",
      o: ["Porque PHP requiere que las dependencias estén instaladas antes de leer el código", "Para que Docker cachee la capa de dependencias y no las reinstale en cada build si solo cambia el código", "Porque composer no puede leer composer.json si el código fuente ya está copiado", "Por seguridad: evita que el código fuente quede en una capa intermedia"], a: 1 },
    { q: "¿Qué hace `docker-compose down -v`?",
      o: ["Solo detiene los contenedores sin borrarlos", "Detiene y elimina los contenedores Y también los volúmenes nombrados del proyecto", "Borra las imágenes construidas para el proyecto", "Reinicia los contenedores con la configuración actualizada"], a: 1 },
    { q: "¿Cuál es la diferencia entre un volumen nombrado y un bind mount?",
      o: ["Son equivalentes con distinta sintaxis", "El volumen nombrado es gestionado por Docker (persistente); el bind mount mapea directamente un directorio del anfitrión", "El bind mount es más lento pero más fiable", "El volumen nombrado solo funciona en Docker Compose, no con docker run"], a: 1 },
    { q: "¿Qué es un multi-stage build en Docker?",
      o: ["Un Dockerfile que se puede ejecutar en múltiples plataformas (arm64, amd64)", "Un Dockerfile con varias fases FROM donde la imagen final solo copia los artefactos necesarios de fases anteriores", "Un build que se ejecuta en paralelo en varios workers", "Un Dockerfile que construye varias imágenes a la vez"], a: 1 },
    { q: "¿Por qué no se deben incluir secretos en una imagen Docker?",
      o: ["Porque Docker no puede cifrar variables de entorno dentro de la imagen", "Porque las capas de la imagen son permanentes e inspeccionables, aunque el secreto se 'borre' en una capa posterior", "Porque los secretos ralentizan el proceso de build", "Solo es un problema si la imagen se sube a un registry público"], a: 1 },
    { q: "¿Por qué PHP-FPM y nginx van en contenedores separados en producción?",
      o: ["Porque Docker no puede ejecutar dos procesos en el mismo contenedor", "Para seguir el principio de un proceso por contenedor, facilitando el escalado y el reemplazo independiente", "Porque nginx no puede comunicarse con PHP-FPM si están en el mismo contenedor", "Por rendimiento: la separación elimina la latencia de red entre ambos"], a: 1 },
    { q: "¿Qué protocolo usa nginx para comunicarse con PHP-FPM?",
      o: ["HTTP interno", "FastCGI (a través de fastcgi_pass)", "Unix sockets exclusivamente (no TCP)", "gRPC para comunicación de alta eficiencia"], a: 1 },
    { q: "¿Qué hace `.dockerignore`?",
      o: ["Excluye ficheros del contexto de build para acelerar la imagen y no exponer ficheros sensibles", "Indica a Docker qué capas de la imagen se pueden ignorar al descargar", "Define qué ficheros se montan como volúmenes automáticamente", "Especifica qué puertos del contenedor no se exponen al exterior"], a: 0 },
    { q: "¿Cómo se comunican entre sí los servicios definidos en docker-compose?",
      o: ["Usando la IP de la máquina anfitriona (127.0.0.1)", "A través de una red privada de Docker, usando el nombre del servicio como hostname", "Mediante variables de entorno que contienen las IPs de cada servicio", "Solo pueden comunicarse si comparten el mismo volumen"], a: 1 },
  ]},

  /* -------- CI/CD (10) -------- */
  "ci-cd": { questions: [
    { q: "¿Cuál es la diferencia entre Integración Continua y Entrega Continua?",
      o: ["Son lo mismo: integración y entrega son sinónimos en este contexto", "CI integra y valida cambios automáticamente; CD añade la entrega automática hasta un entorno listo para producción", "CI es para desarrolladores y CD es para equipos de operaciones", "CI valida el código y CD valida la infraestructura"], a: 1 },
    { q: "¿Por qué integrar ramas tarde es costoso?",
      o: ["Porque los servidores de CI tienen un coste por minuto de ejecución", "Porque cuanto más han divergido las ramas, más conflictos surgen y más difícil es localizar el bug", "Porque los tests de integración tardan más en ejecutarse", "Solo es costoso en equipos grandes con más de 10 desarrolladores"], a: 1 },
    { q: "¿Qué es un runner en GitHub Actions?",
      o: ["El proceso que ejecuta un job del workflow en una máquina efímera", "El desarrollador que aprueba el pipeline antes de que se ejecute", "El script que orquesta el orden de los steps", "La máquina permanente donde se almacenan los artefactos"], a: 0 },
    { q: "¿Qué diferencia hay entre un 'artefacto' y una 'caché' en un pipeline CI?",
      o: ["Son lo mismo pero los artefactos se guardan más tiempo", "El artefacto es el resultado del build que se pasa entre jobs; la caché guarda dependencias para acelerar builds futuros", "La caché se borra tras cada pipeline; el artefacto persiste indefinidamente", "Los artefactos son para binarios y la caché para código fuente"], a: 1 },
    { q: "¿Por qué se ordena el pipeline de 'más barato a más caro'?",
      o: ["Para reducir el tiempo total cuando todos los checks pasan", "Para que si un check barato falla (linting, sintaxis) se detenga el pipeline antes de ejecutar los tests costosos", "Por requisitos de la herramienta de CI: los checks cortos deben ir primero", "Para que el equipo pueda revisar los resultados intermedios más rápido"], a: 1 },
    { q: "En GitHub Actions, ¿qué hace `needs: [lint, test]` en un job?",
      o: ["Ejecuta el job en paralelo con lint y test", "Hace que el job solo se ejecute si lint y test han terminado con éxito", "Indica que el job necesita los mismos secretos que lint y test", "Copia los artefactos de lint y test al workspace del job"], a: 1 },
    { q: "¿Por qué se usa `healthcheck` para MySQL en un pipeline CI?",
      o: ["Para verificar que las credenciales de base de datos son correctas antes de ejecutar tests", "Para que el job espere a que MySQL esté listo para aceptar conexiones antes de ejecutar los tests", "Para monitorizar el rendimiento de la BD durante los tests", "Para que GitHub Actions pueda reiniciar MySQL si falla durante los tests"], a: 1 },
    { q: "¿Cuál es la ventaja de la estrategia blue-green sobre un despliegue directo?",
      o: ["Que consume menos recursos porque se reutiliza la infraestructura existente", "Que el rollback es instantáneo: basta con redirigir el tráfico de nuevo al entorno anterior", "Que elimina el tiempo de inactividad sin necesitar un entorno duplicado", "Que permite desplegar migraciones de BD destructivas de forma segura"], a: 1 },
    { q: "¿Por qué las migraciones destructivas requieren la estrategia 'expand and contract'?",
      o: ["Porque el motor de BD no permite eliminar columnas en producción", "Porque durante el despliegue conviven dos versiones del código que deben operar con el mismo esquema", "Porque las migraciones destructivas requieren reiniciar la base de datos", "Solo aplica con blue-green; en rolling update no es necesario"], a: 1 },
    { q: "¿Qué diferencia hay entre 'despliegue continuo' y 'entrega continua'?",
      o: ["Son lo mismo: 'continuo' y 'continua' se refieren al mismo proceso", "En entrega continua hay una decisión humana antes de ir a producción; en despliegue continuo el paso a producción también es automático", "La entrega continua requiere aprobación del cliente; el despliegue continuo del equipo", "La entrega continua es para equipos pequeños; el despliegue continuo para grandes"], a: 1 },
  ]},

  /* -------- Terminal y Linux (15) -------- */
  "terminal-linux": { questions: [
    { q: "¿Qué significa la filosofía 'todo es un fichero' en Linux?",
      o: ["Que todo el sistema operativo está almacenado en un único fichero comprimido", "Que dispositivos, procesos y conexiones de red se representan como ficheros y se operan con las mismas herramientas", "Que Linux no diferencia entre ficheros de texto y binarios", "Que todos los directorios son en realidad ficheros especiales sin contenido"], a: 1 },
    { q: "¿Qué contiene el directorio `/etc` en el árbol FHS?",
      o: ["Los ejecutables del sistema operativo", "Los ficheros de configuración del sistema y de las aplicaciones instaladas", "Los ficheros temporales que se borran al reiniciar", "Los datos de los usuarios del sistema"], a: 1 },
    { q: "Si un fichero tiene permisos `644`, ¿qué puede hacer el propietario que el grupo no puede?",
      o: ["Ejecutar el fichero", "Escribir en el fichero", "Leer el fichero", "Cambiar los permisos del fichero"], a: 1 },
    { q: "¿Qué hace `chmod +x script.sh`?",
      o: ["Da permisos de escritura al propietario del fichero", "Añade el bit de ejecución al propietario, grupo y otros", "Cambia el propietario del fichero a root", "Añade el bit de ejecución solo al propietario"], a: 1 },
    { q: "¿Por qué `usermod -aG docker david` y no `usermod -G docker david`?",
      o: ["Porque sin `-a` solo añade el grupo si el usuario no tiene ninguno", "Porque sin `-a` reemplaza TODOS los grupos del usuario por `docker`, perdiéndolos", "Porque `-G` en mayúscula requiere `-a` para funcionar correctamente", "Son equivalentes; `-a` es solo un alias deprecado"], a: 1 },
    { q: "¿Qué hace `find . -name '*.log' -mtime +7 -delete`?",
      o: ["Muestra todos los ficheros .log modificados en los últimos 7 días", "Elimina todos los ficheros .log con más de 7 días de antigüedad", "Mueve los ficheros .log de más de 7 días a la papelera", "Comprime todos los ficheros .log con más de 7 días"], a: 1 },
    { q: "¿Qué diferencia hay entre `>` y `>>` en la redirección de shell?",
      o: ["`>` redirige stdout; `>>` redirige stderr", "`>` sobreescribe el fichero de destino; `>>` añade al final sin borrar el contenido existente", "`>` redirige a fichero; `>>` redirige a otro proceso", "Son equivalentes en shells modernas"], a: 1 },
    { q: "¿Qué significa `2>&1` al final de un comando?",
      o: ["Redirige la entrada estándar al stderr", "Redirige el stderr (descriptor 2) al mismo destino que stdout (descriptor 1)", "Ejecuta el comando con doble buffer para mayor velocidad", "Combina stdout y stderr en dos ficheros separados"], a: 1 },
    { q: "¿Qué hace `set -euo pipefail` al inicio de un script bash?",
      o: ["Activa el modo depuración y muestra cada comando antes de ejecutarlo", "Detiene el script en el primer error, trata variables no definidas como error y propaga errores en pipes", "Ejecuta el script en modo silencioso sin mostrar salida", "Activa el modo interactivo aunque el script se ejecute en background"], a: 1 },
    { q: "En cron, ¿qué significa la expresión `*/15 * * * *`?",
      o: ["Ejecutar a las 15 horas de cada día", "Ejecutar cada 15 minutos", "Ejecutar el día 15 de cada mes", "Ejecutar los primeros 15 minutos de cada hora"], a: 1 },
    { q: "¿Por qué los scripts de cron deben usar rutas absolutas para los comandos?",
      o: ["Porque cron solo ejecuta scripts que están en `/usr/local/bin`", "Porque cron se ejecuta con un entorno mínimo que no incluye el PATH habitual del usuario", "Porque las rutas relativas no funcionan en ningún contexto de shell", "Por seguridad para evitar que alguien inyecte un comando falso"], a: 1 },
    { q: "¿Cuál es la diferencia entre SIGTERM y SIGKILL?",
      o: ["No hay diferencia práctica; SIGKILL es solo más rápido", "SIGTERM pide al proceso que termine limpiamente; SIGKILL lo termina de inmediato sin que pueda liberar recursos", "SIGKILL solo funciona como root; SIGTERM puede usarlo cualquier usuario", "SIGTERM solo funciona con procesos propios; SIGKILL puede usarse con cualquier PID"], a: 1 },
    { q: "¿Qué devuelve `ss -tlnp`?",
      o: ["Todos los sockets activos con estadísticas de transferencia", "Los sockets TCP en escucha con el proceso que los usa", "Los sockets UDP activos del sistema", "Solo los sockets de la sesión SSH actual"], a: 1 },
    { q: "¿Qué hace `rsync -avz --delete origen/ destino/`?",
      o: ["Copia el directorio origen en destino sin borrar nada", "Sincroniza origen con destino, borrando en destino los ficheros que ya no existen en origen", "Mueve el directorio origen a destino borrando el original", "Comprime el directorio origen antes de copiarlo a destino"], a: 1 },
    { q: "¿Para qué sirve `~/.ssh/config`?",
      o: ["Para almacenar las claves privadas SSH de forma segura", "Para definir aliases de hosts SSH con sus opciones de conexión (usuario, puerto, clave, etc.)", "Para configurar el servidor SSH local (equivale a /etc/ssh/sshd_config)", "Para autorizar qué IPs pueden conectarse por SSH a la máquina"], a: 1 },
  ]},

  /* -------- Patrones de diseño GoF (15) -------- */
  "patrones-diseno": { questions: [
    { q: "¿Cuál es la diferencia entre Factory Method y Abstract Factory?",
      o: ["Factory Method crea un objeto; Abstract Factory crea una familia de objetos relacionados", "Son lo mismo; Abstract Factory es la versión actualizada de Factory Method", "Factory Method usa herencia y Abstract Factory usa composición exclusivamente", "Abstract Factory es siempre más complejo y debe evitarse"], a: 0 },
    { q: "¿Por qué el patrón Singleton es considerado problemático en testing?",
      o: ["Porque PHP no puede testear clases con estado estático", "Porque mantiene estado global entre tests, creando acoplamiento temporal y resultados no reproducibles", "Porque el Singleton no puede ser instanciado en el contexto de PHPUnit", "Porque los mocks no pueden reemplazar a un Singleton"], a: 1 },
    { q: "¿Qué problema resuelve el patrón Builder?",
      o: ["Que una clase tenga demasiados métodos públicos", "La construcción de objetos complejos con muchos parámetros opcionales, evitando constructores telescópicos", "Que una clase necesite crear instancias de sí misma", "La gestión del ciclo de vida de objetos compartidos"], a: 1 },
    { q: "¿Qué tiene en común el patrón Adapter con un adaptador de enchufes físico?",
      o: ["Que convierte energía de un tipo a otro", "Que permite que dos interfaces incompatibles colaboren sin modificar el código existente", "Que solo puede adaptarse en una dirección", "Que es una solución temporal hasta encontrar una definitiva"], a: 1 },
    { q: "¿Cuál es la diferencia entre Decorator y Proxy?",
      o: ["Son el mismo patrón con distinto nombre", "Decorator añade responsabilidades al objeto decorado; Proxy controla el acceso a él (lazy init, caché, seguridad)", "Decorator modifica el comportamiento y Proxy solo registra las llamadas", "Proxy solo funciona con interfaces; Decorator puede usarse con clases concretas"], a: 1 },
    { q: "¿Qué resuelve el patrón Facade?",
      o: ["Ocultar que un sistema interno usa herencia múltiple", "Proporcionar una interfaz simplificada a un subsistema complejo, reduciendo el acoplamiento de los clientes", "Impedir que un subsistema sea modificado por código externo", "Crear una única instancia compartida de un subsistema complejo"], a: 1 },
    { q: "El patrón Strategy permite:",
      o: ["Que un objeto cambie de clase en tiempo de ejecución", "Definir una familia de algoritmos, encapsular cada uno y hacerlos intercambiables sin modificar el cliente", "Que múltiples objetos compartan el mismo algoritmo sin duplicar código", "Ejecutar algoritmos en paralelo con distintas prioridades"], a: 1 },
    { q: "¿Cómo implementa PHP un patrón Observer de forma nativa en el SPL?",
      o: ["A través de la clase `Observable` y la interfaz `Observer`", "Mediante `SplSubject` / `SplObserver`, aunque en la práctica se implementa a mano o con el EventDispatcher", "PHP no tiene soporte nativo para Observer; siempre se implementa desde cero", "A través de los traits que incluyen los frameworks modernos"], a: 1 },
    { q: "¿Qué problema resuelve el patrón Template Method?",
      o: ["Que una clase padre no pueda llamar a métodos de la clase hija", "Definir el esqueleto de un algoritmo en una clase base, dejando que las subclases implementen pasos concretos", "Que un método pueda ejecutarse antes o después de otro de forma configurable", "Evitar la duplicación de métodos privados entre clases hermanas"], a: 1 },
    { q: "¿Dónde reconoces el patrón Chain of Responsibility en los frameworks PHP?",
      o: ["En el query builder de Eloquent (encadenamiento de métodos)", "En el middleware HTTP de Symfony y Laravel: la petición pasa por una cadena de handlers", "En el bus de comandos de Symfony Messenger (cola de comandos)", "En el contenedor DI que encadena la resolución de dependencias"], a: 1 },
    { q: "En el EventDispatcher de Symfony, ¿qué patrón GoF implementa?",
      o: ["Strategy: cada evento es una estrategia intercambiable", "Observer: el EventDispatcher es el Subject que notifica a los Subscribers (Observers)", "Command: cada evento es un comando que se ejecuta en orden", "Decorator: los listeners decoran el evento antes de pasarlo al siguiente"], a: 1 },
    { q: "¿Por qué el contenedor DI de Symfony usa el patrón Proxy para los lazy services?",
      o: ["Para encriptar las dependencias antes de inyectarlas", "Para controlar el acceso: el proxy se instancia inmediatamente pero la clase real solo se construye cuando se usa por primera vez", "Para que el contenedor pueda interceptar todas las llamadas a los servicios", "Para permitir que el mismo servicio sea compartido entre múltiples contenedores"], a: 1 },
    { q: "¿Qué patrón GoF aplica el principio OCP al añadir nuevos manejadores de pago sin modificar el procesador?",
      o: ["Template Method: cada pago sobreescribe el método de proceso", "Strategy: el procesador delega en una estrategia intercambiable sin cambiar su propio código", "Observer: el procesador notifica a los manejadores cuando llega un pago", "Builder: se construye una cadena de manejadores para cada pago"], a: 1 },
    { q: "¿Qué diferencia al patrón Command del patrón Strategy?",
      o: ["Command y Strategy son lo mismo aplicados a distintos contextos", "Command encapsula una operación como objeto (para encolar, deshacer, registrar); Strategy encapsula un algoritmo intercambiable", "Strategy puede deshacer operaciones; Command no", "Command se usa en sistemas distribuidos; Strategy en sistemas locales"], a: 1 },
    { q: "¿Cuándo NO deberías aplicar un patrón GoF?",
      o: ["Cuando el problema es muy simple y el patrón añadiría complejidad sin aportar valor real", "Cuando el equipo no conoce los patrones GoF de memoria", "Cuando el código ya tiene tests que lo cubren", "Cuando el framework ya tiene su propia implementación del patrón"], a: 0 },
  ]},

  /* -------- Framework por dentro (10) -------- */
  "framework-por-dentro": { questions: [
    { q: "¿Cuál es el primer punto de entrada de una petición HTTP en un setup típico nginx + PHP-FPM?",
      o: ["PHP-FPM: analiza la petición y la enruta al controlador", "nginx: sirve los estáticos y pasa las peticiones PHP a PHP-FPM via FastCGI", "El front controller (index.php): nginx no interviene en el proceso", "El router del framework: compila las rutas antes de que llegue cualquier petición"], a: 1 },
    { q: "¿Qué es el 'front controller' en Symfony/Laravel?",
      o: ["El primer controlador de la aplicación que maneja la ruta raíz `/`", "Un único punto de entrada (`public/index.php`) que arranca el framework y maneja todas las peticiones", "El controlador que gestiona la autenticación antes de cualquier otra ruta", "El router compilado que selecciona el controlador correcto"], a: 1 },
    { q: "¿Qué patrón GoF implementa el ciclo de vida del Kernel de Symfony con sus eventos?",
      o: ["Strategy: cada evento es una estrategia de procesamiento de la petición", "Observer: el Kernel emite eventos y los listeners reaccionan", "Command: cada fase del ciclo es un comando que se ejecuta en orden", "Chain of Responsibility: la petición pasa por una cadena de handlers"], a: 1 },
    { q: "¿Qué es el ArgumentResolver en Symfony?",
      o: ["El componente que compila las rutas antes del arranque", "El componente que resuelve los argumentos del método del controlador antes de invocarlo", "El componente que convierte la respuesta del controlador al formato HTTP", "El servicio que valida que el controlador existe antes de llamarlo"], a: 1 },
    { q: "¿Para qué sirve `fastcgi_finish_request()` en el ciclo de vida de Symfony?",
      o: ["Para cerrar la conexión con la base de datos al final de la petición", "Para enviar la respuesta al cliente y continuar ejecutando código (kernel.terminate) sin bloquear", "Para reiniciar PHP-FPM cuando la petición ha terminado", "Para forzar el vaciado del buffer de salida de PHP"], a: 1 },
    { q: "¿Cuál es la diferencia entre un Event Subscriber y un Event Listener en Symfony?",
      o: ["Son equivalentes; Subscriber es solo el nombre moderno de Listener", "El Subscriber declara en sí mismo los eventos que escucha; el Listener se configura externamente en el contenedor", "El Listener puede escuchar múltiples eventos; el Subscriber solo uno", "El Subscriber es más lento porque usa reflexión para resolver los eventos"], a: 1 },
    { q: "¿Qué garantizan los 'tagged services' de Symfony en relación al principio OCP?",
      o: ["Que los servicios no pueden ser modificados después del arranque del contenedor", "Que se puede añadir comportamiento nuevo sin modificar el código existente que lo consume", "Que solo los servicios con tag pueden ser inyectados en otros servicios", "Que el contenedor verifica que todos los servicios con el mismo tag implementan la misma interfaz"], a: 1 },
    { q: "¿En qué momento se ejecutan los Compiler Passes en Symfony?",
      o: ["En cada petición HTTP, antes de que el router resuelva la ruta", "Una sola vez en tiempo de compilación del contenedor, no en runtime", "Al arrancar el kernel por primera vez, justo antes del primer evento", "Al desplegar, como parte del script de deployment"], a: 1 },
    { q: "¿Cuál es la diferencia entre `register()` y `boot()` en un Service Provider de Laravel?",
      o: ["Son equivalentes; Laravel los llama en el mismo orden", "`register()` solo vincula servicios en el contenedor; `boot()` se ejecuta después de que todos los providers han registrado sus servicios", "`register()` se llama solo en producción; `boot()` en todos los entornos", "`boot()` se llama una vez al desplegar; `register()` en cada petición"], a: 1 },
    { q: "¿Qué característica comparten el middleware de Laravel y el patrón Chain of Responsibility?",
      o: ["Que ambos usan herencia para definir el comportamiento de cada paso", "Que la petición pasa secuencialmente por una cadena de handlers, cada uno pudiendo procesarla o detenerla", "Que ambos requieren un objeto Command para encapsular la petición", "Que el orden de los handlers no importa en ninguno de los dos"], a: 1 },
  ]},

  /* -------- Testing (10) -------- */
  "testing": { questions: [
    { q: "¿Cuál es el ciclo de TDD en orden correcto?",
      o: ["Verde → Rojo → Refactor", "Rojo → Verde → Refactor", "Refactor → Rojo → Verde", "Verde → Refactor → Rojo"], a: 1 },
    { q: "¿Qué diferencia a un test unitario de un test de integración?",
      o: ["El test unitario es más rápido; el de integración prueba más código", "El test unitario prueba una unidad aislada con dobles; el de integración prueba varios componentes reales colaborando", "El test unitario lo escribe el desarrollador; el de integración el equipo de QA", "El test unitario usa assertions; el de integración usa mocks"], a: 1 },
    { q: "¿Qué es un 'stub' en el contexto de los test doubles?",
      o: ["Una clase real simplificada que se usa en lugar de la dependencia en todos los entornos", "Un doble que devuelve respuestas predefinidas a llamadas concretas, sin verificar que fue llamado", "Un doble que registra las llamadas para verificarlas al final del test", "Una implementación alternativa de una interfaz usada en producción"], a: 1 },
    { q: "¿Cuál es la diferencia entre un stub y un mock?",
      o: ["El stub es una clase real; el mock es una clase generada automáticamente", "El stub controla el estado (qué devuelve); el mock también verifica el comportamiento (cómo fue llamado)", "El stub es manual; el mock siempre se genera con una librería", "No hay diferencia práctica; son el mismo concepto con distinto nombre"], a: 1 },
    { q: "¿Qué hace que un test sea 'flaky' (inestable)?",
      o: ["Que tenga muchas assertions", "Que su resultado varía entre ejecuciones por depender de factores externos como el tiempo, el orden o el estado compartido", "Que tarde más de 1 segundo en ejecutarse", "Que use mocks en lugar de la implementación real"], a: 1 },
    { q: "¿Por qué los tests que verifican detalles internos de implementación 'estorban'?",
      o: ["Porque son más lentos que los tests de comportamiento", "Porque se rompen al refactorizar aunque el comportamiento externo no cambie, creando fricción innecesaria", "Porque el compilador no puede verificarlos en tiempo de build", "Porque no aportan información sobre si el código funciona"], a: 1 },
    { q: "¿Qué recomienda la pirámide de tests?",
      o: ["Que todos los tests deben tener el mismo nivel de abstracción", "Muchos tests unitarios (rápidos, baratos), menos de integración y pocos E2E (lentos, costosos)", "Que los tests E2E son los más valiosos y deben ser la mayoría", "Que los mocks deben usarse en todos los niveles de la pirámide"], a: 1 },
    { q: "¿Por qué los tests de una API REST deben testear el comportamiento HTTP y no los detalles del controlador?",
      o: ["Porque el controlador no tiene métodos públicos testeables directamente", "Porque así sobreviven a refactorizaciones internas: si cambias el controlador pero la API se comporta igual, el test sigue verde", "Porque HTTP es el único protocolo que PHPUnit puede simular", "Porque los tests de controlador requieren levantar un servidor web real"], a: 1 },
    { q: "Un test que pasa siempre porque nunca puede fallar se llama:",
      o: ["Test vacío", "Test tautológico o falso positivo", "Test de smoke", "Test de regresión"], a: 1 },
    { q: "¿Cuándo tiene sentido escribir el test DESPUÉS del código (sin TDD)?",
      o: ["Nunca: el test siempre debe ir antes del código", "Cuando se explora una solución desconocida o se trabaja con código legado que hay que caracterizar antes de cambiar", "Solo cuando el tiempo de entrega no permite hacer TDD correctamente", "Cuando el código es muy simple y no necesita ser guiado por tests"], a: 1 },
  ]},

  /* -------- Observabilidad (15) -------- */
  "observabilidad": { questions: [
    { q: "¿Cuáles son los tres pilares de la observabilidad?",
      o: ["CPU, memoria y disco", "Logs, métricas y trazas", "Errores, latencia y throughput", "Sentry, Prometheus y Grafana"], a: 1 },
    { q: "¿Qué ventaja tienen los logs estructurados (JSON) sobre los logs de texto libre?",
      o: ["Que ocupan menos espacio en disco", "Que pueden filtrarse y consultarse por campos específicos de forma eficiente", "Que son más legibles para los humanos en la terminal", "Que los generan automáticamente los frameworks sin configuración"], a: 1 },
    { q: "¿Qué es el 'fingerprinting' en Sentry?",
      o: ["El identificador único de cada petición HTTP para trazarla", "El algoritmo que agrupa errores similares en un único Issue para no saturar el equipo con duplicados", "La firma criptográfica que verifica la autenticidad de los eventos", "El identificador del usuario que provocó el error"], a: 1 },
    { q: "¿Cuál es la diferencia entre un Counter y un Gauge en Prometheus?",
      o: ["Counter mide el tiempo; Gauge mide la cantidad", "Counter solo puede crecer (peticiones totales); Gauge puede subir y bajar (memoria usada, usuarios activos)", "Counter es para valores discretos; Gauge es para valores continuos", "Son equivalentes; la diferencia es solo de convención de nombres"], a: 1 },
    { q: "¿Qué hace la función `rate()` en PromQL?",
      o: ["Devuelve el valor actual del contador", "Calcula la tasa de crecimiento por segundo de un contador sobre un intervalo de tiempo", "Ordena los resultados de mayor a menor tasa", "Filtra las series temporales por su tasa de cambio"], a: 1 },
    { q: "¿En qué se diferencia Loki de Elasticsearch para logs?",
      o: ["Son equivalentes; Loki es la versión de Grafana Labs de Elasticsearch", "Loki solo indexa los metadatos (labels), no el contenido del log, lo que lo hace más ligero y económico", "Loki almacena los logs en formato binario comprimido; Elasticsearch en texto plano", "Elasticsearch es para logs en tiempo real; Loki es para análisis histórico"], a: 1 },
    { q: "En LogQL, ¿qué hace `| json | line_format '{{.level}}: {{.message}}'`?",
      o: ["Filtra los logs que contienen un campo JSON llamado 'level'", "Parsea los logs como JSON y reformatea cada línea usando los campos extraídos", "Convierte los logs de JSON a formato texto plano para mayor legibilidad", "Cuenta el número de logs con campos JSON válidos"], a: 1 },
    { q: "¿Qué es un SLO (Service Level Objective)?",
      o: ["El acuerdo legal de disponibilidad firmado con el cliente (SLA)", "El objetivo interno de nivel de servicio que el equipo se propone cumplir, expresado como porcentaje", "La herramienta de Grafana para medir el rendimiento del servicio", "El umbral de alerta por encima del cual el servicio está degradado"], a: 1 },
    { q: "¿Qué es el 'error budget'?",
      o: ["El presupuesto económico para gestionar incidentes en producción", "El margen de error permitido por el SLO antes de que se considere incumplido", "El número máximo de alertas que el equipo puede recibir por día", "El tiempo máximo de respuesta a un incidente definido en el SLA"], a: 1 },
    { q: "¿Cuál es el problema de alertar sobre causas técnicas en lugar de síntomas de impacto?",
      o: ["Que las alertas de causa son menos fiables que las de síntoma", "Que generan ruido: muchas alertas que no corresponden a un problema real que el usuario note", "Que los sistemas de alerting no pueden acceder a métricas técnicas internas", "Que solo los ingenieros de infraestructura entienden las alertas de causa"], a: 1 },
    { q: "¿Qué es la 'fatiga de alertas' (alert fatigue)?",
      o: ["Que el sistema de alertas falla por exceso de carga", "Que el equipo ignora las alertas por recibir demasiadas, perdiendo la capacidad de reaccionar a los problemas reales", "Que las alertas se repiten por un bug en Alertmanager", "Que el equipo tarda demasiado en configurar las alertas correctamente"], a: 1 },
    { q: "¿Qué es un 'datasource' en Grafana?",
      o: ["Un panel que muestra datos en tiempo real", "La conexión configurada a una fuente de datos (Prometheus, Loki, etc.) que Grafana consulta para sus paneles", "Un fichero JSON que define el layout de un dashboard", "Una variable de Grafana que filtra los datos de todos los paneles"], a: 1 },
    { q: "¿Cuándo usarías un Histogram en Prometheus en lugar de un Summary?",
      o: ["Cuando necesitas percentiles exactos sin configuración previa", "Cuando quieres calcular percentiles agregados entre múltiples instancias del servicio", "Cuando el rango de valores observados es predecible y fijo", "Cuando necesitas calcular la tasa de cambio de los valores observados"], a: 1 },
    { q: "¿Qué captura Sentry además de la excepción en sí?",
      o: ["Solo el stack trace y el mensaje de error", "El contexto completo: usuario, petición, variables de entorno, breadcrumbs (eventos previos) y release", "Solo los errores de nivel crítico", "Los logs de la última hora antes del error"], a: 1 },
    { q: "¿Qué es un 'breadcrumb' en Sentry?",
      o: ["Un enlace en el dashboard para navegar hasta el código que causó el error", "Una traza de los eventos que ocurrieron justo antes del error, en orden cronológico", "La ruta en el filesystem donde se generó el error", "El identificador de la versión del código que causó el error"], a: 1 },
  ]},

  /* -------- PHPUnit (12) -------- */
  "phpunit": { questions: [
    { q: "¿Cuál es el orden correcto de las fases de un test (patrón AAA)?",
      o: ["Arrange → Act → Assert", "Assert → Arrange → Act", "Act → Assert → Arrange", "Setup → Execute → Verify → Teardown"], a: 0 },
    { q: "¿Para qué sirven los Data Providers en PHPUnit?",
      o: ["Para cargar datos de fixtures desde ficheros CSV o JSON", "Para ejecutar el mismo test con múltiples conjuntos de datos de entrada y salida esperada", "Para compartir datos entre tests de la misma suite", "Para generar datos aleatorios en cada ejecución del test"], a: 1 },
    { q: "¿Cuándo se ejecuta el método `setUp()` en PHPUnit?",
      o: ["Una vez antes de todos los tests de la clase", "Antes de CADA método de test, creando un entorno limpio para cada uno", "Una vez al principio de la suite completa", "Solo si el test anterior falló"], a: 1 },
    { q: "¿Cuál es la diferencia entre `setUp()` y `setUpBeforeClass()`?",
      o: ["No hay diferencia; `setUpBeforeClass()` es un alias deprecado", "`setUp()` se ejecuta antes de cada test; `setUpBeforeClass()` se ejecuta una vez antes de todos los tests de la clase", "`setUpBeforeClass()` es para fixtures de BD; `setUp()` es para datos en memoria", "`setUpBeforeClass()` es estático y `setUp()` de instancia, pero ambos se ejecutan antes de cada test"], a: 1 },
    { q: "¿Qué método de PHPUnit usas para que un mock lance una excepción al ser llamado?",
      o: ["->willReturn(new Exception(...))", "->willThrowException(new ExcepcionEspecifica(...))", "->throwsException(ExcepcionEspecifica::class)", "->expects($this->throwException(...))"], a: 1 },
    { q: "¿Qué diferencia hay entre `createMock()` y `createStub()` en PHPUnit?",
      o: ["`createMock()` genera verificaciones de llamadas automáticamente; `createStub()` no", "`createStub()` permite configurar respuestas; `createMock()` no", "`createMock()` es para interfaces; `createStub()` para clases concretas", "Son equivalentes; `createStub()` es el alias moderno de `createMock()`"], a: 0 },
    { q: "¿Qué hace `$this->expectException(InvalidArgumentException::class)` en un test?",
      o: ["Indica que el test pasará si NO se lanza esa excepción", "Indica que el test espera que se lance esa excepción; si no se lanza, el test falla", "Captura la excepción para que no interrumpa el test", "Solo verifica que la clase de excepción existe, no que sea lanzada"], a: 1 },
    { q: "¿Qué mide la cobertura de código (code coverage)?",
      o: ["La calidad de los tests: si son buenos o malos", "Qué porcentaje de líneas (o ramas) del código son ejecutadas por los tests", "Cuántos bugs quedan sin detectar", "Si el código cumple los requisitos funcionales"], a: 1 },
    { q: "¿Por qué el 100% de cobertura no garantiza ausencia de bugs?",
      o: ["Porque la cobertura solo funciona con tests unitarios, no de integración", "Porque la cobertura mide si el código se ejecuta, no si las assertions verifican el comportamiento correcto", "Porque PHPUnit no puede medir la cobertura de código heredado", "Porque algunos bugs solo aparecen en producción"], a: 1 },
    { q: "¿Por qué en tests de integración con BD se usa una base de datos de test?",
      o: ["Porque la base de datos de desarrollo es de solo lectura", "Para que los tests sean reproducibles y no contaminen ni dependan de datos de desarrollo", "Porque PHPUnit no puede conectarse a la base de datos de desarrollo", "Por rendimiento: la BD de test es más pequeña"], a: 1 },
    { q: "¿Cuál es el riesgo de ejecutar tests de integración contra la BD de producción?",
      o: ["Que los tests serán más lentos por el volumen de datos", "Que los tests pueden modificar, borrar o insertar datos reales, causando daño irreversible", "Que PHPUnit no puede conectarse a BD en producción por restricciones de red", "Solo es un riesgo si el usuario de BD tiene permisos de escritura"], a: 1 },
    { q: "¿Qué estrategia garantiza que cada test de integración empieza con un estado conocido?",
      o: ["Ejecutar los tests en orden determinista para que cada uno limpie tras de sí", "Envolver cada test en una transacción que se revierte al finalizar, o recrear el esquema entre tests", "Usar solo SELECT en los tests de integración para no modificar datos", "Generar datos aleatorios únicos en cada test para evitar colisiones"], a: 1 },
  ]},

  /* -------- Programar con IA (10) -------- */
  "programar-con-ia": { questions: [
    { q: "¿Qué es un LLM (Large Language Model)?",
      o: ["Un sistema experto basado en reglas que simula el razonamiento humano", "Un modelo estadístico entrenado en grandes corpus de texto que predice el siguiente token de una secuencia", "Un motor de búsqueda mejorado con capacidad de generar respuestas", "Un sistema de base de datos vectorial que almacena conocimiento semántico"], a: 1 },
    { q: "¿Qué es la 'ventana de contexto' de un LLM?",
      o: ["El tiempo que tarda el modelo en procesar una petición", "La cantidad máxima de texto (tokens) que el modelo puede considerar en una sola inferencia", "El historial de conversaciones almacenado en el servidor del proveedor", "La memoria a largo plazo que el modelo construye sobre el usuario"], a: 1 },
    { q: "¿Qué es el 'tool calling' (function calling)?",
      o: ["La capacidad del modelo de ejecutar código Python directamente", "La capacidad del modelo de invocar funciones externas definidas por el desarrollador para obtener información o realizar acciones", "Una técnica de prompting que describe funciones en el prompt", "El mecanismo por el que el modelo llama a otros modelos especializados"], a: 1 },
    { q: "¿Qué es el protocolo MCP (Model Context Protocol)?",
      o: ["Un estándar de Anthropic para medir la calidad de los modelos de IA", "Un protocolo abierto que estandariza cómo los modelos de IA se conectan a herramientas y fuentes de datos externas", "Un protocolo de comunicación entre modelos de distintos proveedores", "El formato de mensajes usado en la API de Claude"], a: 1 },
    { q: "¿Qué es RAG (Retrieval-Augmented Generation)?",
      o: ["Una técnica de fine-tuning para especializar el modelo en un dominio", "Una técnica que combina búsqueda de información relevante con generación, para que el modelo responda con datos actualizados sin reentrenarlo", "Un modelo que genera texto y luego lo recupera de una caché para reutilizarlo", "El proceso de evaluar la calidad de las respuestas generadas por un LLM"], a: 1 },
    { q: "¿Cuál es la diferencia entre fine-tuning y prompting para adaptar un LLM?",
      o: ["El fine-tuning es más barato y rápido que el prompting", "El fine-tuning ajusta los pesos del modelo con nuevos datos; el prompting guía al modelo en runtime sin cambiar los pesos", "El prompting modifica el modelo; el fine-tuning solo ajusta el comportamiento en producción", "No hay diferencia práctica; el fine-tuning es simplemente un prompt más largo"], a: 1 },
    { q: "¿Por qué no se debe confiar ciegamente en el código generado por una IA?",
      o: ["Porque los modelos de IA tienen prohibido generar código seguro", "Porque el modelo puede generar código plausible pero incorrecto, desactualizado o con vulnerabilidades de seguridad", "Porque el código generado no compila en entornos de producción", "Porque los LLMs no pueden generar código en todos los lenguajes"], a: 1 },
    { q: "¿Qué es un 'agente' de IA en el contexto del desarrollo de software?",
      o: ["Un modelo entrenado específicamente para programar", "Un sistema que combina un LLM con herramientas y un bucle de planificación-acción-observación para completar tareas complejas", "Un asistente de IA que solo puede responder preguntas sin ejecutar acciones", "Un pipeline de ML que procesa código automáticamente"], a: 1 },
    { q: "¿Qué riesgo introduce el 'prompt injection' en sistemas con agentes de IA?",
      o: ["Que el modelo genera prompts más largos de lo esperado", "Que contenido malicioso en las entradas del agente puede manipular sus acciones para realizar operaciones no autorizadas", "Que el sistema de monitorización no puede registrar las acciones del agente", "Que el agente entra en un bucle infinito al procesar ciertos tipos de entrada"], a: 1 },
    { q: "¿Qué es el 'alucinamiento' (hallucination) en los LLMs?",
      o: ["Cuando el modelo responde más lento de lo esperado por exceso de carga", "Cuando el modelo genera información plausible pero factualmente incorrecta con total confianza", "Cuando el modelo no puede completar una tarea y lo indica explícitamente", "Cuando el modelo repite la misma frase varias veces en su respuesta"], a: 1 },
  ]},

  /* -------- Fundamentos de CS (20) -------- */
  "fundamentos": { questions: [
    { q: "¿Cuántos bits tiene un byte?",
      o: ["4", "8", "16", "10"], a: 1 },
    { q: "¿Por qué `0.1 + 0.2 !== 0.3` en la mayoría de los lenguajes de programación?",
      o: ["Porque los lenguajes modernos usan aritmética entera por defecto", "Porque los números en coma flotante siguen el estándar IEEE-754 y algunos decimales no tienen representación exacta en binario", "Porque el operador `!==` es más estricto que `!=`", "Porque el compilador optimiza las operaciones de suma de forma imprecisa"], a: 1 },
    { q: "¿Qué es la complejidad O(log n)?",
      o: ["Un algoritmo que divide el problema a la mitad en cada paso", "Un algoritmo que examina cada elemento una vez", "Un algoritmo que compara cada elemento con todos los demás", "Un algoritmo que crece linealmente con la entrada"], a: 0 },
    { q: "¿Qué estructura de datos usarías para búsqueda en O(1) promedio?",
      o: ["Array ordenado con búsqueda binaria", "Hashmap / tabla hash", "Árbol B", "Lista enlazada ordenada"], a: 1 },
    { q: "¿Por qué un índice B-tree en base de datos acelera las búsquedas?",
      o: ["Porque comprime los datos, reduciendo el número de páginas a leer", "Porque organiza los valores en un árbol equilibrado que permite buscar en O(log n) en lugar de O(n)", "Porque mantiene los datos en memoria RAM permanentemente", "Porque agrupa los datos por su valor hash para acceso directo"], a: 1 },
    { q: "¿Qué garantiza la Atomicidad (A de ACID)?",
      o: ["Que cada dato solo existe en un lugar de la base de datos", "Que una transacción se ejecuta completamente o no se ejecuta en absoluto", "Que múltiples transacciones concurrentes no se interfieren", "Que los datos persisten incluso ante fallos del sistema"], a: 1 },
    { q: "¿Qué es la anomalía 'dirty read' y qué nivel de aislamiento mínimo la previene?",
      o: ["Leer un dato que otro proceso está a punto de modificar; lo previene READ UNCOMMITTED", "Leer datos de una transacción que aún no ha confirmado y podría revertirse; lo previene READ COMMITTED", "Leer el mismo dato dos veces y obtener resultados distintos; lo previene REPEATABLE READ", "Ver filas nuevas en una segunda lectura dentro de la misma transacción; lo previene SERIALIZABLE"], a: 1 },
    { q: "¿Cuál es la diferencia entre un proceso y un hilo?",
      o: ["Los hilos son procesos más ligeros sin diferencias de aislamiento", "Un proceso tiene su propio espacio de memoria aislado; los hilos de un mismo proceso comparten el heap y las variables globales", "Un proceso puede ejecutarse en paralelo; un hilo solo en un núcleo", "Los procesos son gestionados por el OS y los hilos por la máquina virtual"], a: 1 },
    { q: "¿Por qué PHP-FPM usa múltiples procesos en lugar de múltiples hilos?",
      o: ["Porque PHP no soporta la creación de hilos", "Por el modelo 'shared-nothing': cada proceso tiene su propio estado, evitando condiciones de carrera entre peticiones", "Porque los procesos son más rápidos que los hilos en sistemas Linux", "Por compatibilidad con extensiones C que no son thread-safe"], a: 1 },
    { q: "¿Qué es una condición de carrera (race condition)?",
      o: ["Un bug que solo aparece bajo alta carga del servidor", "Cuando el resultado de una operación depende del orden de ejecución de operaciones concurrentes no sincronizadas", "Cuando dos procesos intentan usar la misma CPU al mismo tiempo", "Un error de rendimiento causado por hilos que compiten por el mismo recurso"], a: 1 },
    { q: "¿Para qué tipo de problemas es ideal el event loop?",
      o: ["Para aplicaciones con mucho procesamiento CPU en paralelo", "Para gestionar muchas conexiones concurrentes con poco CPU: I/O-bound con operaciones no bloqueantes", "Para el bucle principal de PHP-FPM que gestiona peticiones", "Para gestionar eventos de dominio en DDD"], a: 1 },
    { q: "¿Qué hace el DNS?",
      o: ["Cifra las comunicaciones entre el cliente y el servidor", "Traduce nombres de dominio legibles en direcciones IP numéricas", "Gestiona las cookies de sesión entre cliente y servidor", "Verifica la autenticidad de los certificados TLS"], a: 1 },
    { q: "¿Qué garantiza TLS en una conexión HTTPS?",
      o: ["Que el servidor es el más rápido disponible para el cliente", "Que la comunicación está cifrada y que el servidor es quien dice ser", "Que los datos llegan en orden y sin duplicados", "Que no hay intermediarios entre el cliente y el servidor"], a: 1 },
    { q: "¿Qué afirma el teorema CAP?",
      o: ["Que un sistema distribuido puede ser Consistente, Available y tolerante a Particiones simultáneamente", "Que en presencia de una partición de red, un sistema debe elegir entre Consistencia y Disponibilidad", "Que la Consistencia siempre debe priorizarse sobre la Disponibilidad en producción", "Que los sistemas distribuidos no pueden garantizar ninguna de las tres propiedades simultáneamente"], a: 1 },
    { q: "¿Cuál es la diferencia entre hashing y cifrado?",
      o: ["El hashing es reversible; el cifrado no lo es", "El hashing es unidireccional (no reversible); el cifrado es bidireccional (reversible con la clave)", "El hashing es más lento pero más seguro que el cifrado", "Son sinónimos; ambos convierten datos en una representación distinta"], a: 1 },
    { q: "¿Por qué no se deben almacenar contraseñas con MD5 o SHA-256 directamente?",
      o: ["Porque PHP no soporta esos algoritmos en versiones modernas", "Porque son rápidos, lo que permite ataques de fuerza bruta; las contraseñas deben hashearse con algoritmos lentos como bcrypt", "Porque producen colisiones demasiado frecuentes para cadenas cortas", "Porque no son estándares aprobados por la industria para contraseñas"], a: 1 },
    { q: "¿Qué es una inyección SQL y cómo se previene?",
      o: ["Un ataque que modifica el HTML de la respuesta; se previene con CSP", "Un ataque donde el atacante inyecta SQL en una entrada de usuario para manipular la consulta; se previene con consultas parametrizadas", "Un ataque que sobrecarga el servidor con consultas legítimas; se previene con rate limiting", "Un error de configuración de la base de datos; se previene con permisos restrictivos"], a: 1 },
    { q: "¿Qué es el XSS (Cross-Site Scripting)?",
      o: ["Un ataque que intercepta la comunicación entre el cliente y el servidor", "Un ataque donde se inyecta JavaScript malicioso en páginas web que otros usuarios ven", "Un ataque que roba cookies de sesión cambiando la URL del servidor", "Un ataque de fuerza bruta sobre las contraseñas de usuarios"], a: 1 },
    { q: "¿Qué es la idempotencia en el contexto de APIs y sistemas distribuidos?",
      o: ["Que una operación siempre devuelve el mismo resultado independientemente de cuándo se llame", "Que ejecutar una operación varias veces produce el mismo efecto que ejecutarla una sola vez", "Que la operación se puede deshacer después de ejecutarse", "Que la operación es atómica y no puede interrumpirse"], a: 1 },
    { q: "¿Qué es la consistencia eventual en sistemas distribuidos?",
      o: ["Que el sistema garantiza que todos los nodos tienen el mismo dato en todo momento", "Que si dejas de hacer escrituras, eventualmente todos los nodos convergen al mismo valor", "Que el sistema puede perder datos en caso de fallo de red", "Que las lecturas siempre devuelven el dato más reciente"], a: 1 },
  ]},

  /* -------- Diseño y arquitectura (15) -------- */
  "diseno-y-arquitectura": { questions: [
    { q: "¿Qué es la arquitectura hexagonal?",
      o: ["Una arquitectura que divide el sistema en 6 capas horizontales", "Una arquitectura que protege el dominio de los detalles externos usando puertos (interfaces) y adaptadores (implementaciones)", "Una variante de microservicios donde cada servicio tiene 6 responsabilidades máximo", "Una arquitectura centrada en las operaciones CRUD"], a: 1 },
    { q: "¿Cuál es la diferencia entre un puerto y un adaptador en la arquitectura hexagonal?",
      o: ["El puerto es la implementación y el adaptador es la interfaz", "El puerto es la abstracción (interfaz) que el dominio define; el adaptador es la implementación concreta que vive fuera", "Los puertos son para la entrada y los adaptadores para la salida", "Son sinónimos; se usan indistintamente según el framework"], a: 1 },
    { q: "¿Qué garantiza la regla de dependencia en la arquitectura hexagonal?",
      o: ["Que las dependencias apuntan siempre hacia afuera (hacia la infraestructura)", "Que las dependencias apuntan siempre hacia adentro: la infraestructura depende del dominio, nunca al revés", "Que el dominio no tiene ninguna dependencia con ningún otro módulo", "Que los adaptadores no pueden comunicarse entre sí directamente"], a: 1 },
    { q: "¿Qué es el 'Ubiquitous Language' en DDD?",
      o: ["Un lenguaje de programación diseñado específicamente para modelar dominios", "Un vocabulario común compartido por desarrolladores y expertos de dominio que se refleja en el código", "El conjunto de patrones tácticos de DDD (entidades, agregados, etc.)", "El lenguaje usado en los comentarios del código para documentar el dominio"], a: 1 },
    { q: "¿Qué es un Bounded Context en DDD estratégico?",
      o: ["Un módulo del sistema con acceso limitado a la base de datos", "Un límite explícito dentro del cual un modelo de dominio tiene un significado concreto y consistente", "Un microservicio con su propio despliegue y base de datos", "El contexto de ejecución de un agregado raíz"], a: 1 },
    { q: "¿Qué diferencia a una Entidad de un Value Object en DDD?",
      o: ["La Entidad tiene métodos; el Value Object solo tiene propiedades", "La Entidad tiene identidad propia (id); el Value Object se define por sus atributos y es inmutable", "La Entidad persiste en base de datos; el Value Object no persiste", "El Value Object puede cambiar de valor; la Entidad es inmutable"], a: 1 },
    { q: "¿Qué es un Agregado en DDD?",
      o: ["Un conjunto de tablas relacionadas en la base de datos", "Un clúster de objetos de dominio tratados como una unidad para las operaciones de consistencia, con una raíz que controla el acceso", "Una clase que agrega comportamiento de múltiples entidades", "Un servicio que coordina operaciones entre múltiples contextos acotados"], a: 1 },
    { q: "¿Por qué el Agregado Raíz es el único punto de entrada al agregado?",
      o: ["Para facilitar la serialización del agregado a JSON", "Para garantizar los invariantes de negocio: todos los cambios pasan por la raíz que puede verificar las reglas", "Para que el ORM pueda gestionar el ciclo de vida de todos los objetos del agregado", "Por rendimiento: reduce el número de consultas a la base de datos"], a: 1 },
    { q: "¿Qué son los Domain Events?",
      o: ["Excepciones de dominio que se propagan cuando ocurre un error de negocio", "Mensajes que registran algo significativo que ocurrió en el dominio, expresados en tiempo pasado", "Comandos que el dominio envía a la infraestructura para ejecutar acciones", "Los eventos del ciclo HTTP del framework que afectan al dominio"], a: 1 },
    { q: "¿Qué separa CQRS (Command Query Responsibility Segregation)?",
      o: ["Las peticiones autenticadas de las anónimas", "El modelo de escritura (Commands, que cambian estado) del modelo de lectura (Queries, que no cambian estado)", "Los comandos de negocio de los comandos de infraestructura", "Las operaciones síncronas de las asíncronas"], a: 1 },
    { q: "¿Cuál es el beneficio de separar el modelo de lectura del de escritura en CQRS?",
      o: ["Que el código es más conciso porque no hay duplicación", "Que cada modelo puede optimizarse de forma independiente: el de escritura para consistencia, el de lectura para rendimiento", "Que elimina la necesidad de una base de datos relacional", "Que los tests son más sencillos porque las operaciones están separadas"], a: 1 },
    { q: "¿Qué es Event Sourcing?",
      o: ["Una técnica para suscribirse a eventos de dominio de otros bounded contexts", "Un patrón donde el estado de un agregado se deriva de la secuencia de eventos que le han ocurrido, en lugar de almacenar el estado actual", "Una forma de implementar el event bus para comunicar contextos", "El patrón de usar Domain Events como única forma de comunicación entre agregados"], a: 1 },
    { q: "¿Qué ventaja única ofrece Event Sourcing frente al almacenamiento del estado actual?",
      o: ["Que los queries son más rápidos porque no necesitan JOINs", "Que el historial completo de cambios es parte del modelo: puedes reconstruir el estado en cualquier punto del tiempo", "Que elimina la necesidad de migraciones de esquema", "Que los agregados no necesitan un identificador único"], a: 1 },
    { q: "¿Qué es una 'proyección' en el contexto de Event Sourcing?",
      o: ["El proceso de serializar los eventos a JSON para almacenarlos", "La transformación de la secuencia de eventos en una representación optimizada para lectura (el modelo de lectura de CQRS)", "El proceso de replicar los eventos a otros servicios del sistema", "La validación que verifica que los eventos son consistentes entre sí"], a: 1 },
    { q: "¿Qué complejidad añade CQRS + Event Sourcing que no tiene la arquitectura hexagonal simple?",
      o: ["Que requiere más clases y más código, justificado solo en dominios con alta complejidad y requisitos de auditoría", "Que es imposible usar un ORM con Event Sourcing", "Que el equipo debe dominar tres o más lenguajes de programación", "Que el despliegue requiere infraestructura de mensajería que no existe en la nube"], a: 0 },
  ]},

  /* -------- Go (12) -------- */
  "go": { questions: [
    { q: "¿Cuánta memoria ocupa una goroutine al arrancar, frente a un thread del SO?",
      o: ["La misma: ambos empiezan con 1 MB de stack", "Una goroutine empieza con ~2 KB; un thread del SO suele necesitar 1-8 MB", "Los goroutines no tienen stack propio; usan el del thread principal", "La goroutine ocupa más porque el scheduler de Go añade overhead"], a: 1 },
    { q: "¿Qué ocurre al enviar un valor a un canal sin buffer cuando no hay receptor esperando?",
      o: ["El valor se descarta silenciosamente", "La goroutine emisora se bloquea hasta que otra goroutine recibe el valor", "El programa lanza un panic inmediatamente", "El valor se encola internamente hasta que haya receptor"], a: 1 },
    { q: "¿Para qué sirve `defer` en Go?",
      o: ["Para ejecutar una función en otro goroutine", "Para aplazar la ejecución de una llamada a función hasta que la función que la contiene retorne", "Para marcar una función como de baja prioridad en el scheduler", "Para definir el comportamiento de limpieza de una interfaz"], a: 1 },
    { q: "¿Cómo implementa un tipo una interfaz en Go?",
      o: ["Usando la palabra clave `implements` seguida del nombre de la interfaz", "Declarando explícitamente que implementa la interfaz en la cabecera del struct", "Implementando todos los métodos de la interfaz; Go lo verifica automáticamente sin declaración explícita", "Heredando de un tipo base que ya implementa la interfaz"], a: 2 },
    { q: "¿Cuál es el patrón idiomático de manejo de errores en Go?",
      o: ["Usar panic/recover como equivalente a try/catch", "Retornar el error como último valor de la función y comprobar `if err != nil` en el caller", "Enviar el error a un canal de errores global", "Wrappear toda la lógica en un bloque `defer func() { if r := recover(); r != nil { } }()`"], a: 1 },
    { q: "¿Qué diferencia hay entre un canal con buffer de tamaño 1 y uno sin buffer?",
      o: ["No hay diferencia: ambos bloquean al emisor si no hay receptor", "El canal con buffer de 1 permite que el emisor envíe un valor sin bloquearse si el buffer está vacío; el sin buffer bloquea siempre hasta que haya receptor", "El canal con buffer es más lento porque gestiona memoria adicional", "El canal sin buffer no puede usarse entre goroutines distintas"], a: 1 },
    { q: "¿Qué hace `select` en Go?",
      o: ["Selecciona el case más rápido de una lista de operaciones de canal, bloqueándose si ninguno está listo", "Ejecuta todos los cases en paralelo y retorna el resultado del primero que termina", "Es el equivalente a switch/case pero para tipos de datos", "Selecciona una goroutine aleatoria del pool del scheduler"], a: 0 },
    { q: "¿Para qué sirve `sync.WaitGroup`?",
      o: ["Para limitar el número de goroutines que pueden ejecutarse simultáneamente", "Para esperar a que un conjunto de goroutines terminen antes de continuar", "Para sincronizar el acceso a variables compartidas entre goroutines", "Para establecer un timeout en operaciones de canal"], a: 1 },
    { q: "¿Qué es el embedding en Go?",
      o: ["Una forma de importar paquetes externos directamente en el struct", "Incluir un tipo dentro de otro struct para promover sus campos y métodos sin herencia", "Incrustar código ensamblador dentro de funciones Go para optimización", "Una directiva del compilador para inlinear funciones pequeñas"], a: 1 },
    { q: "¿Cuál es la diferencia entre `new(T)` y `make(T)`?",
      o: ["Son equivalentes; `new` es la forma antigua y `make` la moderna", "`new` aloca memoria para cualquier tipo y retorna un puntero al zero value; `make` inicializa slices, maps y canales con estado interno usable", "`make` aloca en el stack y `new` en el heap", "`new` retorna el valor directamente y `make` retorna un puntero"], a: 1 },
    { q: "¿Qué garantiza `context.Context` en Go?",
      o: ["Que las goroutines accedan a variables globales de forma segura", "Un mecanismo para propagar cancelación, deadlines y valores entre funciones y goroutines de forma coordinada", "Que las funciones async se ejecuten en orden FIFO", "El aislamiento de memoria entre goroutines concurrentes"], a: 1 },
    { q: "¿Qué ventaja tiene el patrón de tabla de tests (table-driven tests) en Go?",
      o: ["Que los tests se ejecutan más rápido que los tests convencionales", "Que se pueden definir múltiples casos de prueba como datos, evitando repetir la lógica de test y facilitando añadir nuevos casos", "Que permite usar mocks sin definir interfaces adicionales", "Que los tests generan automáticamente cobertura del 100%"], a: 1 },
  ]},

};
