import { execSync } from 'node:child_process';
const root = process.env.PLAYWRIGHT_ROOT ?? execSync('npm root -g').toString().trim();
const { chromium } = await import(`${root}/playwright/index.mjs`);
const [url, shotDir] = process.argv.slice(2);
const browser = await chromium.launch();
const context = await browser.newContext({ viewport: { width: 1280, height: 900 }, serviceWorkers: 'block' });
const page = await context.newPage();
const errors = [];
page.on('pageerror', (error) => errors.push(error.message));
await page.goto(url);
await page.waitForSelector('#home-new .mini-card');
const read = (shelf) => page.$$eval(`#${shelf} .mini-card__desc`, (nodes) => nodes.map((node) => node.textContent.trim()));
const novedades = await read('home-new');
const destacados = await read('home-popular');
const soloDigitos = [...novedades, ...destacados].filter((text) => /^\d+$/.test(text));
await page.locator('#home-new').screenshot({ path: `${shotDir}/novedades.png` });
await page.locator('#home-popular').screenshot({ path: `${shotDir}/destacados.png` });
const input = page.locator('#home-search input, input[type="search"]').first();
await input.fill('docker');
await page.waitForTimeout(1500);
const resultados = await page.$$eval('#home-results .mini-card__desc', (nodes) => nodes.map((node) => node.textContent.trim()));
const resultadosConDigitos = resultados.filter((text) => /^\d+$/.test(text));
const conFragmento = await page.$$eval('#home-results .mini-card__desc--match', (nodes) => nodes.length);
await page.locator('#home-results').screenshot({ path: `${shotDir}/busqueda-docker.png` });
console.log(JSON.stringify({ novedades, destacados, soloDigitos: soloDigitos.length, resultados: resultados.length, resultadosConDigitos: resultadosConDigitos.length, conFragmento, errors }, null, 2));
await browser.close();
