import { execSync } from 'node:child_process';
const root = execSync('npm root -g').toString().trim();
const { chromium } = await import(`${root}/playwright/index.mjs`);
const browser = await chromium.launch();
const page = await (await browser.newContext({ serviceWorkers: 'block' })).newPage();
const r = {};
await page.goto(process.argv[2] + 'curso.html?slug=ia-por-dentro');
await page.waitForTimeout(500);
r.curso = (await page.locator('main').innerText()).replace(/\s+/g, ' ').slice(0, 160);
r.leccion = (await page.goto(process.argv[2] + 'tutorials/llm-muestreo.html')).status();
await page.goto(process.argv[2] + 'rutas.html');
r.rutaConCurso = await page.evaluate(() => document.body.innerText.includes('La IA por dentro'));
console.log(JSON.stringify(r, null, 2));
await browser.close();
