import { execSync } from 'node:child_process';
const root = execSync('npm root -g').toString().trim();
const { chromium } = await import(`${root}/playwright/index.mjs`);
const browser = await chromium.launch();
const page = await (await browser.newContext({ viewport: { width: 1280, height: 900 }, serviceWorkers: 'block' })).newPage();
const base = process.argv[2];
const r = {};
await page.goto(base + 'tutorials/llm-atencion-y-contexto.html');
r.clavesValores = await page.evaluate(() => document.body.innerText.includes('cada token se resume en una clave'));
await page.goto(base + 'tutorials/llm-de-texto-a-tokens.html');
r.entradaSalida = await page.evaluate(() => document.body.innerText.includes('Entrada y salida no cuestan lo mismo'));
await page.goto(base + 'tutorials/llm-entrenamiento.html');
r.cuartaEtapa = await page.evaluate(() => document.body.innerText.includes('Refuerzo verificable'));
await page.locator('#preferencias ~ .diagram').first().screenshot({ path: process.argv[3] + '/diagrama-etapas.png' });
await page.goto(base + 'curso.html?slug=ia-por-dentro');
await page.waitForTimeout(400);
r.retos = await page.$$eval('.practica__reto .practica__title, .practica__reto h3, .practica__reto strong', (els) => [...new Set(els.map((e) => e.textContent.trim()))].slice(0, 6));
r.numRetos = await page.locator('.practica__reto').count();
console.log(JSON.stringify(r, null, 2));
await browser.close();
